// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using IMGR.Database.Control.Entities;
using Microsoft.EntityFrameworkCore;

namespace IMGR.Database.Control;

public partial class LegacyControlDbContext : DbContext
{
    public LegacyControlDbContext(DbContextOptions<LegacyControlDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ClientSource> ClientSources { get; set; }

    public virtual DbSet<CompanyAutopayFile> CompanyAutopayFiles { get; set; }

    public virtual DbSet<CompanyAutopayFileSignature> CompanyAutopayFileSignatures { get; set; }

    public virtual DbSet<CompanyDatabase> CompanyDatabases { get; set; }

    public virtual DbSet<CompanyEnrollmentForm> CompanyEnrollmentForms { get; set; }

    public virtual DbSet<CompanyInbox> CompanyInboxes { get; set; }

    public virtual DbSet<CompanyInboxAttachment> CompanyInboxAttachments { get; set; }

    public virtual DbSet<CompanyMPFFile> CompanyMPFFiles { get; set; }

    public virtual DbSet<CompanyMPFFileSignature> CompanyMPFFileSignatures { get; set; }

    public virtual DbSet<DatabaseServer> DatabaseServers { get; set; }

    public virtual DbSet<EmailLog> EmailLogs { get; set; }

    public virtual DbSet<HSBCBankPaymentCode> HSBCBankPaymentCodes { get; set; }

    public virtual DbSet<HSBCExchangeProfile> HSBCExchangeProfiles { get; set; }

    public virtual DbSet<MPFEnrollmentForm> MPFEnrollmentForms { get; set; }

    public virtual DbSet<MPFFollowUpAgreement> MPFFollowUpAgreements { get; set; }

    public virtual DbSet<MPFSchemeEnrollmentForm> MPFSchemeEnrollmentForms { get; set; }

    public virtual DbSet<PublicHoliday> PublicHolidays { get; set; }

    public virtual DbSet<StatutoryHoliday> StatutoryHolidays { get; set; }

    public virtual DbSet<SystemFunction> SystemFunctions { get; set; }

    public virtual DbSet<SystemParameter> SystemParameters { get; set; }

    public virtual DbSet<TextTransformation> TextTransformations { get; set; }

    public virtual DbSet<Token> Tokens { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserApiToken> UserApiTokens { get; set; }

    public virtual DbSet<UserFunction> UserFunctions { get; set; }

    public virtual DbSet<iMGRAnnouncement> iMGRAnnouncements { get; set; }

    public virtual DbSet<iStaffUserDeactivationLog> iStaffUserDeactivationLogs { get; set; }

    public virtual DbSet<temp1> temp1s { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ClientSource>(entity =>
        {
            entity.ToTable("ClientSource");

            entity.Property(e => e.ClientSourceName).HasMaxLength(255);
        });

        modelBuilder.Entity<CompanyAutopayFile>(entity =>
        {
            entity.ToTable("CompanyAutopayFile");

            entity.Property(e => e.CompanyAutopayFile1stSignDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyAutopayFile1stSignEmpName).HasMaxLength(50);
            entity.Property(e => e.CompanyAutopayFile2ndSignDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyAutopayFile2ndSignEmpName).HasMaxLength(50);
            entity.Property(e => e.CompanyAutopayFileBankAccountNo).HasMaxLength(30);
            entity.Property(e => e.CompanyAutopayFileBankCode).HasMaxLength(255);
            entity.Property(e => e.CompanyAutopayFileBatchAmount).HasColumnType("decimal(20, 2)");
            entity.Property(e => e.CompanyAutopayFileBranchCode).HasMaxLength(30);
            entity.Property(e => e.CompanyAutopayFileCancelDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyAutopayFileConfirmDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyAutopayFileConsolidateDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyAutopayFileDataFileRelativePath).HasColumnType("ntext");
            entity.Property(e => e.CompanyAutopayFileReportFileRelativePath).HasColumnType("ntext");
            entity.Property(e => e.CompanyAutopayFileStatus).HasMaxLength(1);
            entity.Property(e => e.CompanyAutopayFileSubmitDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyAutopayFileSubmitEmpID)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "df_CompanyAutopayFile_CompanyAutopayFileSubmitEmpID");
            entity.Property(e => e.CompanyAutopayFileSubmitEmpName).HasMaxLength(50);
            entity.Property(e => e.CompanyAutopayFileTransactionReference).HasMaxLength(20);
            entity.Property(e => e.CompanyAutopayFileValueDate).HasColumnType("datetime");
            entity.Property(e => e.CompanyAutopayFileVersion).HasMaxLength(10);
        });

        modelBuilder.Entity<CompanyAutopayFileSignature>(entity =>
        {
            entity.ToTable("CompanyAutopayFileSignature");

            entity.Property(e => e.CompanyAutopayFileSignatureDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyAutopayFileSignatureUserName).HasMaxLength(255);
        });

        modelBuilder.Entity<CompanyDatabase>(entity =>
        {
            entity.HasKey(e => e.CompanyDBID);

            entity.ToTable("CompanyDatabase");

            entity.Property(e => e.ClientSourceID)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "df_CompanyDatabase_ClientSourceID");
            entity.Property(e => e.CompanyConvenientCode).HasMaxLength(255);
            entity.Property(e => e.CompanyDBAuthorizationCode).HasMaxLength(255);
            entity.Property(e => e.CompanyDBClientAddress).HasColumnType("ntext");
            entity.Property(e => e.CompanyDBClientBank).HasMaxLength(100);
            entity.Property(e => e.CompanyDBClientCode).HasMaxLength(255);
            entity.Property(e => e.CompanyDBClientContactPerson).HasMaxLength(255);
            entity.Property(e => e.CompanyDBClientName).HasMaxLength(255);
            entity.Property(e => e.CompanyDBProductKey).HasMaxLength(255);
            entity.Property(e => e.CompanyDBResetDefaultUserLoginID).HasMaxLength(255);
            entity.Property(e => e.CompanyDBResetDefaultUserPassword).HasMaxLength(255);
            entity.Property(e => e.CompanyDBSchemaName).HasMaxLength(255);
            entity.Property(e => e.CompanyDBTrialKey).HasMaxLength(255);
        });

        modelBuilder.Entity<CompanyEnrollmentForm>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("CompanyEnrollmentForm");

            entity.HasIndex(e => e.ErSubmitDateTime, "IDX_CompanyEnrollmentForm_ErSubmitDateTime");

            entity.Property(e => e.EmpEngFullName).HasMaxLength(255);
            entity.Property(e => e.EmpNo).HasMaxLength(40);
            entity.Property(e => e.ErSubmitDateTime).HasColumnType("datetime");
            entity.Property(e => e.FormStatus).HasMaxLength(20);
            entity.Property(e => e.ToHSBCDateTime).HasColumnType("datetime");
            entity.Property(e => e.UndoDateTime).HasColumnType("datetime");
            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<CompanyInbox>(entity =>
        {
            entity.ToTable("CompanyInbox");

            entity.Property(e => e.CompanyInboxCreateDate).HasColumnType("datetime");
            entity.Property(e => e.CompanyInboxDeleteDate).HasColumnType("datetime");
            entity.Property(e => e.CompanyInboxExpiryDate).HasColumnType("datetime");
            entity.Property(e => e.CompanyInboxMessage).HasColumnType("ntext");
            entity.Property(e => e.CompanyInboxReadDate).HasColumnType("datetime");
            entity.Property(e => e.CompanyInboxSubject).HasMaxLength(100);
        });

        modelBuilder.Entity<CompanyInboxAttachment>(entity =>
        {
            entity.ToTable("CompanyInboxAttachment");

            entity.Property(e => e.CompanyInboxAttachmentOriginalFileName).HasMaxLength(250);
            entity.Property(e => e.CompanyInboxAttachmentStoredFileName).HasMaxLength(250);
        });

        modelBuilder.Entity<CompanyMPFFile>(entity =>
        {
            entity.ToTable("CompanyMPFFile");

            entity.Property(e => e.CompanyMPFFile1stSignDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyMPFFile1stSignEmpName).HasMaxLength(50);
            entity.Property(e => e.CompanyMPFFile2ndSignDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyMPFFile2ndSignEmpName).HasMaxLength(50);
            entity.Property(e => e.CompanyMPFFileBatchAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CompanyMPFFileCancelDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyMPFFileConfirmDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyMPFFileConsolidateDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyMPFFileDataFileRelativePath).HasColumnType("ntext");
            entity.Property(e => e.CompanyMPFFileDescription).HasMaxLength(255);
            entity.Property(e => e.CompanyMPFFileEmployerID).HasMaxLength(11);
            entity.Property(e => e.CompanyMPFFileFileType).HasMaxLength(255);
            entity.Property(e => e.CompanyMPFFilePayCenter).HasMaxLength(4);
            entity.Property(e => e.CompanyMPFFileReportFileRelativePath).HasColumnType("ntext");
            entity.Property(e => e.CompanyMPFFileStatus).HasMaxLength(1);
            entity.Property(e => e.CompanyMPFFileSubmitDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyMPFFileSubmitEmpID)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "df_CompanyMPFFile_CompanyMPFFileSubmitEmpID");
            entity.Property(e => e.CompanyMPFFileSubmitEmpName).HasMaxLength(50);
            entity.Property(e => e.CompanyMPFFileTransactionReference).HasMaxLength(20);
            entity.Property(e => e.CompanyMPFFileTrusteeCode).HasMaxLength(255);
            entity.Property(e => e.CompanyMPFFileVersion).HasMaxLength(10);
        });

        modelBuilder.Entity<CompanyMPFFileSignature>(entity =>
        {
            entity.ToTable("CompanyMPFFileSignature");

            entity.Property(e => e.CompanyMPFFileSignatureDateTime).HasColumnType("datetime");
            entity.Property(e => e.CompanyMPFFileSignatureUserName).HasMaxLength(255);
        });

        modelBuilder.Entity<DatabaseServer>(entity =>
        {
            entity.HasKey(e => e.DBServerID);

            entity.ToTable("DatabaseServer");

            entity.Property(e => e.DBServerCode).HasMaxLength(255);
            entity.Property(e => e.DBServerDBType).HasMaxLength(100);
            entity.Property(e => e.DBServerLocation).HasMaxLength(255);
            entity.Property(e => e.DBServerPassword).HasMaxLength(255);
            entity.Property(e => e.DBServerSAPassword).HasMaxLength(255);
            entity.Property(e => e.DBServerSAUserID).HasMaxLength(255);
            entity.Property(e => e.DBServerUserID).HasMaxLength(255);
        });

        modelBuilder.Entity<EmailLog>(entity =>
        {
            entity.ToTable("EmailLog");

            entity.Property(e => e.EmailBody).HasColumnType("ntext");
            entity.Property(e => e.EmailLogEndTime).HasColumnType("datetime");
            entity.Property(e => e.EmailLogErrorMessage).HasColumnType("ntext");
            entity.Property(e => e.EmailLogStartTime).HasColumnType("datetime");
            entity.Property(e => e.EmailLogToAddress).HasColumnType("ntext");
            entity.Property(e => e.EmailSubject).HasMaxLength(255);
        });

        modelBuilder.Entity<HSBCBankPaymentCode>(entity =>
        {
            entity.ToTable("HSBCBankPaymentCode");

            entity.Property(e => e.HSBCBankPaymentCode1)
                .HasMaxLength(255)
                .HasColumnName("HSBCBankPaymentCode");
            entity.Property(e => e.HSBCBankPaymentCodeAutoPayInOutFlag).HasMaxLength(1);
            entity.Property(e => e.HSBCBankPaymentCodeBankAccountNo).HasMaxLength(255);
        });

        modelBuilder.Entity<HSBCExchangeProfile>(entity =>
        {
            entity.ToTable("HSBCExchangeProfile");

            entity.Property(e => e.HSBCExchangeProfileBankCode).HasMaxLength(100);
            entity.Property(e => e.HSBCExchangeProfileRemoteProfileID).HasMaxLength(255);
        });

        modelBuilder.Entity<MPFEnrollmentForm>(entity =>
        {
            entity.ToTable("MPFEnrollmentForm");

            entity.Property(e => e.MPFEnrollmentFormCode).HasMaxLength(50);
            entity.Property(e => e.MPFEnrollmentFormSubmissionEffFr).HasColumnType("datetime");
            entity.Property(e => e.MPFEnrollmentFormSubmissionEffTo).HasColumnType("datetime");
        });

        modelBuilder.Entity<MPFFollowUpAgreement>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("MPFFollowUpAgreement");

            entity.Property(e => e.AgreementDateTime).HasColumnType("datetime");
            entity.Property(e => e.ChineseName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.HKID).HasMaxLength(255);
            entity.Property(e => e.HomePhoneNo).HasMaxLength(255);
            entity.Property(e => e.Mobile).HasMaxLength(255);
            entity.Property(e => e.OtherName).HasMaxLength(255);
            entity.Property(e => e.SendToHSBCDateTime).HasColumnType("datetime");
            entity.Property(e => e.Surname).HasMaxLength(255);
            entity.Property(e => e.TrusteeCode).HasMaxLength(20);
            entity.Property(e => e.WorkPhoneNo).HasMaxLength(255);
            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<MPFSchemeEnrollmentForm>(entity =>
        {
            entity.ToTable("MPFSchemeEnrollmentForm");

            entity.HasIndex(e => e.MPFSchemeCode, "IDX_MPFSchemeEnrollmentForm");

            entity.Property(e => e.EnrollmentFormName).HasMaxLength(50);
            entity.Property(e => e.MPFSchemeCode)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<PublicHoliday>(entity =>
        {
            entity.ToTable("PublicHoliday");

            entity.Property(e => e.PublicHolidayDate).HasColumnType("datetime");
            entity.Property(e => e.PublicHolidayDesc).HasMaxLength(100);
        });

        modelBuilder.Entity<StatutoryHoliday>(entity =>
        {
            entity.ToTable("StatutoryHoliday");

            entity.Property(e => e.StatutoryHolidayDate).HasColumnType("datetime");
            entity.Property(e => e.StatutoryHolidayDesc).HasMaxLength(100);
        });

        modelBuilder.Entity<SystemFunction>(entity =>
        {
            entity.HasKey(e => e.FunctionID);

            entity.ToTable("SystemFunction");

            entity.Property(e => e.Description).HasMaxLength(100);
            entity.Property(e => e.FunctionCode).HasMaxLength(10);
        });

        modelBuilder.Entity<SystemParameter>(entity =>
        {
            entity.HasKey(e => e.ParameterCode);

            entity.ToTable("SystemParameter");

            entity.Property(e => e.ParameterCode).HasMaxLength(100);
            entity.Property(e => e.ParameterDesc).HasMaxLength(200);
            entity.Property(e => e.ParameterValue).HasMaxLength(200);
        });

        modelBuilder.Entity<TextTransformation>(entity =>
        {
            entity.ToTable("TextTransformation");

            entity.Property(e => e.TextTransformationOriginalString).HasMaxLength(255);
            entity.Property(e => e.TextTransformationReplacedTo).HasMaxLength(255);
        });

        modelBuilder.Entity<Token>(entity =>
        {
            entity.HasKey(e => e.TokenID).HasName("PK_TokenMapping");

            entity.ToTable("Token");

            entity.HasIndex(e => new { e.TokenValue, e.TokenExpiryDateTime }, "NonClusteredIndex-20171230-195501");

            entity.HasIndex(e => e.TokenBatchID, "NonClusteredIndex-20181008-170705");

            entity.Property(e => e.ActionType).HasMaxLength(20);
            entity.Property(e => e.AdditionalInfo).HasColumnType("ntext");
            entity.Property(e => e.RecordCreatedDateTime).HasColumnType("datetime");
            entity.Property(e => e.RecordLastModifiedDateTime).HasColumnType("datetime");
            entity.Property(e => e.TokenBatchID).HasMaxLength(50);
            entity.Property(e => e.TokenCreationDateTime).HasColumnType("datetime");
            entity.Property(e => e.TokenExerciseDateTime).HasColumnType("datetime");
            entity.Property(e => e.TokenExpiryDateTime).HasColumnType("datetime");
            entity.Property(e => e.TokenValue)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.ExpiryDate).HasColumnType("datetime");
            entity.Property(e => e.LoginID).HasMaxLength(255);
            entity.Property(e => e.UserAccountStatus).HasMaxLength(1);
            entity.Property(e => e.UserChangePasswordDate).HasColumnType("datetime");
            entity.Property(e => e.UserChangePasswordUnit).HasMaxLength(1);
            entity.Property(e => e.UserName).HasMaxLength(255);
            entity.Property(e => e.UserPassword).HasMaxLength(255);
        });

        modelBuilder.Entity<UserApiToken>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK_UserApiTokenid");

            entity.ToTable("UserApiToken");

            entity.Property(e => e.RefreshToken).HasMaxLength(100);
            entity.Property(e => e.RefreshTokenCreateDateTime).HasColumnType("datetime");
            entity.Property(e => e.RefreshTokenExpiryDateTime).HasColumnType("datetime");
            entity.Property(e => e.Username).HasMaxLength(256);
        });

        modelBuilder.Entity<UserFunction>(entity =>
        {
            entity.ToTable("UserFunction");
        });

        modelBuilder.Entity<iMGRAnnouncement>(entity =>
        {
            entity.ToTable("iMGRAnnouncement");

            entity.Property(e => e.iMGRAnnouncementCode)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.iMGRAnnouncementEffectiveDateFr).HasColumnType("datetime");
            entity.Property(e => e.iMGRAnnouncementEffectiveDateTo).HasColumnType("datetime");
        });

        modelBuilder.Entity<iStaffUserDeactivationLog>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("iStaffUserDeactivationLog");

            entity.Property(e => e.AppClientCode).HasMaxLength(255);
            entity.Property(e => e.AppUserEmail).HasMaxLength(255);
            entity.Property(e => e.AppUserEmpNo).HasMaxLength(255);
            entity.Property(e => e.AppUserPhoneNumber).HasMaxLength(255);
            entity.Property(e => e.AspNetUserId).HasMaxLength(450);
            entity.Property(e => e.DeactivationDateTime).HasColumnType("datetime");
            entity.Property(e => e.EmpTermLastDate).HasColumnType("datetime");
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<temp1>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("temp1");

            entity.Property(e => e.Paymentcode).HasMaxLength(5);
            entity.Property(e => e.ac).HasMaxLength(15);
            entity.Property(e => e.autoid).ValueGeneratedOnAdd();
            entity.Property(e => e.dir).HasMaxLength(1);
            entity.Property(e => e.profileID).HasMaxLength(15);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
