// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class AccountsIntegrationERContribution
{
    public int PlanContributionID { get; set; }

    public int PlanID { get; set; }

    public int? EmploymentTypeID { get; set; }

    public string ContributionType { get; set; }

    public string ContributionDesc { get; set; }

    public string LedgerSegmentCode { get; set; }

    public string BudgetSegmentCode { get; set; }
}