// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class AccountsIntegrationPlan
{
    public int PlanID { get; set; }

    public string PlanDescription { get; set; }

    public string PlanPaymentBudgetAccountCode { get; set; }

    public string PlanBankAccountCode { get; set; }
}