// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class ALProrataRoundingRule
{
    public int ALProrataRoundingRuleID { get; set; }

    public string ALProrataRoundingRuleCode { get; set; }

    public string ALProrataRoundingRuleDesc { get; set; }
}