// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class ALProrataRoundingRuleDetail
{
    public int ALProrataRoundingRuleDetailID { get; set; }

    public int ALProrataRoundingRuleID { get; set; }

    public float ALProrataRoundingRuleDetailRangeTo { get; set; }

    public float ALProrataRoundingRuleDetailRoundTo { get; set; }
}