// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class AsyncTask
{
    public int AsyncTaskID { get; set; }

    public string TaskCode { get; set; }

    public string TaskDescription { get; set; }

    public string TaskHandler { get; set; }
}