// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class AttendanceFormula
{
    public int AttendanceFormulaID { get; set; }

    public string AttendanceFormulaCode { get; set; }

    public string AttendanceFormulaDesc { get; set; }

    public string AttendanceFormulaType { get; set; }

    public int? AttendanceFormulaPayFormID { get; set; }

    public float? AttendanceFormulaWorkHourPerDay { get; set; }

    public decimal? AttendanceFormulaFixedRate { get; set; }

    public int? AttendanceFormulaDecimalPlace { get; set; }

    public string AttendanceFormulaRoundingRule { get; set; }

    public bool? AttendanceFormulaIsUseRosterCodeForDefaultWorkHourPerDay { get; set; }
}