// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class AttendanceRecord
{
    public int AttendanceRecordID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? AttendanceRecordDate { get; set; }

    public int? RosterCodeID { get; set; }

    public int? RosterTableID { get; set; }

    public DateTime? AttendanceRecordWorkStart { get; set; }

    public DateTime? AttendanceRecordWorkEnd { get; set; }

    public DateTime? AttendanceRecordLunchOut { get; set; }

    public DateTime? AttendanceRecordLunchIn { get; set; }

    public int? AttendanceRecordCalculateLateMins { get; set; }

    public int? AttendanceRecordActualLateMins { get; set; }

    public int? AttendanceRecordCalculateEarlyLeaveMins { get; set; }

    public int? AttendanceRecordActualEarlyLeaveMins { get; set; }

    public int? AttendanceRecordCalculateOvertimeMins { get; set; }

    public int? AttendanceRecordActualOvertimeMins { get; set; }

    public float? AttendanceRecordCalculateWorkingDay { get; set; }

    public float? AttendanceRecordActualWorkingDay { get; set; }

    public float? AttendanceRecordCalculateWorkingHour { get; set; }

    public float? AttendanceRecordActualWorkingHour { get; set; }

    public bool? AttendanceRecordIsAbsent { get; set; }

    public string AttendanceRecordRemark { get; set; }

    public bool? AttendanceRecordOverrideBonusEntitled { get; set; }

    public bool? AttendanceRecordHasBonus { get; set; }

    public string AttendanceRecordExtendData { get; set; }

    public int? AttendanceRecordCalculateLunchTimeMins { get; set; }

    public int? AttendanceRecordActualLunchTimeMins { get; set; }

    public string AttendanceRecordWorkStartLocation { get; set; }

    public string AttendanceRecordWorkEndLocation { get; set; }

    public string AttendanceRecordLunchOutLocation { get; set; }

    public string AttendanceRecordLunchInLocation { get; set; }

    public int? AttendanceRecordCalculateLunchLateMins { get; set; }

    public int? AttendanceRecordActualLunchLateMins { get; set; }

    public int? AttendanceRecordCalculateLunchEarlyLeaveMins { get; set; }

    public int? AttendanceRecordActualLunchEarlyLeaveMins { get; set; }

    public DateTime? AttendanceRecordRosterCodeInTimeOverride { get; set; }

    public DateTime? AttendanceRecordRosterCodeOutTimeOverride { get; set; }

    public DateTime? AttendanceRecordRosterCodeLunchStartTimeOverride { get; set; }

    public DateTime? AttendanceRecordRosterCodeLunchEndTimeOverride { get; set; }

    public int? AttendanceRecordWorkStartTimeCardRecordID { get; set; }

    public int? AttendanceRecordWorkEndTimeCardRecordID { get; set; }

    public int? AttendanceRecordLunchOutTimeCardRecordID { get; set; }

    public int? AttendanceRecordLunchInTimeCardRecordID { get; set; }

    public int? AttendanceRecordCalculateLunchOvertimeMins { get; set; }

    public int? AttendanceRecordActualLunchOvertimeMins { get; set; }

    public int? LeaveAppID { get; set; }

    public bool? AttendanceRecordWorkOnRestDay { get; set; }

    public int? AttendanceRecordWaivedLateMins { get; set; }
}