// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class AttendancePlan
{
    public int AttendancePlanID { get; set; }

    public string AttendancePlanCode { get; set; }

    public string AttendancePlanDesc { get; set; }

    public int? AttendancePlanOTFormula { get; set; }

    public int? AttendancePlanLateFormula { get; set; }

    public int? AttendancePlanOTMinsUnit { get; set; }

    public int? AttendancePlanLateMinsUnit { get; set; }

    public int? AttendancePlanOTPayCodeID { get; set; }

    public int? AttendancePlanLatePayCodeID { get; set; }

    public string AttendancePlanOTMinsRoundingRule { get; set; }

    public string AttendancePlanLateMinsRoundingRule { get; set; }

    public bool? AttendancePlanLateIncludeEarlyLeave { get; set; }

    public int? AttendancePlanBonusMaxTotalLateCount { get; set; }

    public int? AttendancePlanBonusMaxTotalLateMins { get; set; }

    public int? AttendancePlanBonusMaxTotalEarlyLeaveCount { get; set; }

    public int? AttendancePlanBonusMaxTotalEarlyLeaveMins { get; set; }

    public int? AttendancePlanBonusMaxTotalSLWithMedicalCertificate { get; set; }

    public int? AttendancePlanBonusMaxTotalSLWithoutMedicalCertificate { get; set; }

    public int? AttendancePlanBonusMaxTotalAbsentCount { get; set; }

    public int? AttendancePlanBonusMaxTotalNonFullPayCasualLeave { get; set; }

    public int? AttendancePlanBonusMaxTotalInjuryLeave { get; set; }

    public float? AttendancePlanBonusAmount { get; set; }

    public string AttendancePlanBonusAmountUnit { get; set; }

    public int? AttendancePlanBonusPayCodeID { get; set; }

    public float? AttendancePlanBonusOTAmount { get; set; }

    public bool? AttendancePlanUseBonusAmountByRecurringPayment { get; set; }

    public bool? AttendancePlanProrataBonusforNewJoin { get; set; }

    public bool? AttendancePlanProrataBonusforTerminated { get; set; }

    public int? AttendancePlanAbsentProrataPayFormID { get; set; }

    public bool? AttendancePlanCompensateLateByOT { get; set; }

    public bool? AttendancePlanTerminatedHasBonus { get; set; }

    public float? AttendancePlanBonusPartialPaidPercent { get; set; }

    public int? AttendancePlanBonusPartialPaidMaxTotalLateCount { get; set; }

    public int? AttendancePlanBonusPartialPaidMaxTotalLateMins { get; set; }

    public int? AttendancePlanBonusPartialPaidMaxTotalEarlyLeaveCount { get; set; }

    public int? AttendancePlanBonusPartialPaidMaxTotalEarlyLeaveMins { get; set; }

    public int? AttendancePlanBonusPartialPaidMaxTotalSLWithMedicalCertificate { get; set; }

    public int? AttendancePlanBonusPartialPaidMaxTotalSLWithoutMedicalCertificate { get; set; }

    public int? AttendancePlanBonusPartialPaidMaxTotalAbsentCount { get; set; }

    public int? AttendancePlanBonusPartialPaidMaxTotalNonFullPayCasualLeave { get; set; }

    public int? AttendancePlanBonusPartialPaidMaxTotalInjuryLeave { get; set; }

    public float? AttendancePlanOTRateMultiplier { get; set; }

    public bool? AttendancePlanOTGainAsCompensationLeaveEntitle { get; set; }

    public bool? AttendancePlanLateIncludeLunchLate { get; set; }

    public bool? AttendancePlanLateIncludeLunchEarlyLeave { get; set; }

    public bool? AttendancePlanBonusMaxTotalLateCountIncludeLunch { get; set; }

    public bool? AttendancePlanBonusMaxTotalLateMinsIncludeLunch { get; set; }

    public bool? AttendancePlanBonusMaxTotalEarlyLeaveCountIncludeLunch { get; set; }

    public bool? AttendancePlanBonusMaxTotalEarlyLeaveMinsIncludeLunch { get; set; }

    public bool? AttendancePlanBonusPartialPaidMaxTotalLateCountIncludeLunch { get; set; }

    public bool? AttendancePlanBonusPartialPaidMaxTotalLateMinsIncludeLunch { get; set; }

    public bool? AttendancePlanBonusPartialPaidMaxTotalEarlyLeaveCountIncludeLunch { get; set; }

    public bool? AttendancePlanBonusPartialPaidMaxTotalEarlyLeaveMinsIncludeLunch { get; set; }

    public bool? AttendancePlanOTIncludeLunchOvertime { get; set; }

    public int? AttendancePlanLateMaxTotalToleranceMins { get; set; }
}