// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class AttendancePreparationProcess
{
    public int AttendancePreparationProcessID { get; set; }

    public DateTime? AttendancePreparationProcessMonth { get; set; }

    public string AttendancePreparationProcessDesc { get; set; }

    public string AttendancePreparationProcessStatus { get; set; }

    public DateTime? AttendancePreparationProcessPayDate { get; set; }

    public int? AttendancePreparationProcessEmpCount { get; set; }

    public DateTime? AttendancePreparationProcessPeriodFr { get; set; }

    public DateTime? AttendancePreparationProcessPeriodTo { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }
}