// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class AttendancePlanAdditionalPayment
{
    public int AttendancePlanAdditionalPaymentID { get; set; }

    public int? AttendancePlanID { get; set; }

    public int? PaymentCodeID { get; set; }

    public double? AttendancePlanAdditionalPaymentAmount { get; set; }

    public int? AttendancePlanAdditionalPaymentMaxLateMins { get; set; }

    public int? AttendancePlanAdditionalPaymentMaxEarlyLeaveMins { get; set; }

    public int? AttendancePlanAdditionalPaymentMinOvertimeMins { get; set; }

    public DateTime? AttendancePlanAdditionalPaymentRosterAcrossTime { get; set; }
}