// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class AttendancePreparationImportBatch
{
    public int AttendancePreparationImportBatchID { get; set; }

    public DateTime? AttendancePreparationImportBatchDateTime { get; set; }

    public int? AttendancePreparationImportBatchUploadedBy { get; set; }

    public string AttendancePreparationImportBatchRemark { get; set; }
}