// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class AuditTrail
{
    public int AuditTrailID { get; set; }

    public int? UserID { get; set; }

    public int? FunctionID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? ParentAuditTrailID { get; set; }
}