// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class AuthorizerDelegate
{
    public int AuthorizerDelegateID { get; set; }

    public int? EmpID { get; set; }

    public int? AuthorizerDelegateEmpID { get; set; }
}