// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class AuthorizationGroup
{
    public int AuthorizationGroupID { get; set; }

    public string AuthorizationCode { get; set; }

    public string AuthorizationDesc { get; set; }

    public int? AuthorizationGroupIsApproveEEInfo { get; set; }

    public int? AuthorizationGroupIsApproveLeave { get; set; }

    public bool? AuthorizationGroupIsReceiveOtherGrpAlert { get; set; }

    public string AuthorizationGroupEmailAddress { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }
}