// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class AuthorizationWorkFlowDetail
{
    public int AuthorizationWorkFlowDetailID { get; set; }

    public int? AuthorizationWorkFlowID { get; set; }

    public int? AuthorizationWorkFlowIndex { get; set; }

    public int? AuthorizationGroupID { get; set; }
}