// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class Authorizer
{
    public int AuthorizerID { get; set; }

    public int? EmpID { get; set; }

    public int? AuthorizationGroupID { get; set; }

    public bool? AuthorizerIsReadOnly { get; set; }

    public bool? IsEmailNoti { get; set; }

    public bool? IsAppNoti { get; set; }

    public bool? IsSelfApproval { get; set; }
}