// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class AuthorizationWorkFlow
{
    public int AuthorizationWorkFlowID { get; set; }

    public string AuthorizationWorkFlowCode { get; set; }

    public string AuthorizationWorkFlowDescription { get; set; }

    public int? CompanyID { get; set; }
}