// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class AVCPlan
{
    public int AVCPlanID { get; set; }

    public string AVCPlanCode { get; set; }

    public string AVCPlanDesc { get; set; }

    public bool? AVCPlanEmployerResidual { get; set; }

    public bool? AVCPlanEmployeeResidual { get; set; }

    public bool? AVCPlanUseMPFExemption { get; set; }

    public bool? AVCPlanJoinDateStart { get; set; }

    public bool? AVCPlanContributeMaxAge { get; set; }

    public bool? AVCPlanContributeMinRI { get; set; }

    public decimal? AVCPlanMaxEmployerVC { get; set; }

    public decimal? AVCPlanMaxEmployeeVC { get; set; }

    public int? AVCPlanEmployerDecimalPlace { get; set; }

    public string AVCPlanEmployerRoundingRule { get; set; }

    public int? AVCPlanEmployeeDecimalPlace { get; set; }

    public string AVCPlanEmployeeRoundingRule { get; set; }

    public bool? AVCPlanNotRemoveContributionFromTopUp { get; set; }

    public decimal? AVCPlanEmployerResidualCAP { get; set; }

    public decimal? AVCPlanEmployeeResidualCAP { get; set; }

    public string AVCPlanMonthOptionForEffectiveContribution { get; set; }

    public string AVCTrusteeReference1 { get; set; }

    public string AVCTrusteeReference2 { get; set; }
}