// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class AVCPlanPaymentConsider
{
    public int AVCPlanPaymentConsiderID { get; set; }

    public int? AVCPlanID { get; set; }

    public int? PaymentCodeID { get; set; }

    public int? AVCPlanPaymentConsiderAfterMPF { get; set; }
}