// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class AVCPlanPaymentFloor
{
    public int AVCPlanPaymentFloorID { get; set; }

    public int? AVCPlanID { get; set; }

    public int? PaymentCodeID { get; set; }

    public float? AVCPlanPaymentFloorAmount { get; set; }
}