// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class AVCPlanDetail
{
    public int AVCPlanDetailID { get; set; }

    public int? AVCPlanID { get; set; }

    public int? AVCPlanDetailYearOfService { get; set; }

    public decimal? AVCPlanDetailERBelowRI { get; set; }

    public decimal? AVCPlanDetailERAboveRI { get; set; }

    public decimal? AVCPlanDetailERFix { get; set; }

    public decimal? AVCPlanDetailEEBelowRI { get; set; }

    public decimal? AVCPlanDetailEEAboveRI { get; set; }

    public decimal? AVCPlanDetailEEFix { get; set; }
}