// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class BankList
{
    public int BankCodeID { get; set; }

    public string BankCode { get; set; }

    public string BankName { get; set; }
}