// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class BankFileDailySeq
{
    public int BankFileDailySeqID { get; set; }

    public string BankCode { get; set; }

    public DateTime BankFileDate { get; set; }

    public int BankFileSeq { get; set; }
}