// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class BankSwift
{
    public int BankSwiftID { get; set; }

    public string BankCode { get; set; }

    public string BankName { get; set; }

    public string SwiftCode { get; set; }

    public string LocalClearingCode { get; set; }

    public string CountryCode { get; set; }
}