// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class BenefitPlan
{
    public int BenefitPlanID { get; set; }

    public string BenefitPlanCode { get; set; }

    public string BenefitPlanDesc { get; set; }

    public string BenefitPlanERPaymentBaseMethod { get; set; }

    public int? BenefitPlanERPaymentCodeID { get; set; }

    public string BenefitPlanERMultiplier { get; set; }

    public decimal? BenefitPlanERAmount { get; set; }

    public string BenefitPlanEEPaymentBaseMethod { get; set; }

    public int? BenefitPlanEEPaymentCodeID { get; set; }

    public string BenefitPlanEEMultiplier { get; set; }

    public decimal? BenefitPlanEEAmount { get; set; }

    public string BenefitPlanSpousePaymentBaseMethod { get; set; }

    public int? BenefitPlanSpousePaymentCodeID { get; set; }

    public string BenefitPlanSpouseMultiplier { get; set; }

    public decimal? BenefitPlanSpouseAmount { get; set; }

    public string BenefitPlanChildPaymentBaseMethod { get; set; }

    public int? BenefitPlanChildPaymentCodeID { get; set; }

    public string BenefitPlanChildMultiplier { get; set; }

    public decimal? BenefitPlanChildAmount { get; set; }
}