// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class BonusProcess
{
    public int BonusProcessID { get; set; }

    public DateTime? BonusProcessMonth { get; set; }

    public string BonusProcessDesc { get; set; }

    public string BonusProcessStatus { get; set; }

    public int? BonusProcessPayCodeID { get; set; }

    public DateTime? BonusProcessPayDate { get; set; }

    public DateTime? BonusProcessSalaryMonth { get; set; }

    public DateTime? BonusProcessPeriodFr { get; set; }

    public DateTime? BonusProcessPeriodTo { get; set; }

    public decimal? BonusProcessStdRate { get; set; }

    public decimal? BonusProcessRank1 { get; set; }

    public decimal? BonusProcessRank2 { get; set; }

    public decimal? BonusProcessRank3 { get; set; }

    public decimal? BonusProcessRank4 { get; set; }

    public decimal? BonusProcessRank5 { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }
}