// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class CasualScheme
{
    public int CasualSchemeID { get; set; }

    public string CasualSchemeCode { get; set; }

    public string CasualSchemeDesc { get; set; }

    public string CasualSchemeTrusteeCode { get; set; }
}