// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class CasualRecord
{
    public int CasualRecordID { get; set; }

    public int EmpPayrollID { get; set; }

    public int CasualPlanID { get; set; }

    public DateTime CasualRecPeriodFr { get; set; }

    public DateTime CasualRecPeriodTo { get; set; }

    public string CasualRecType { get; set; }

    public decimal? CasualRecCalMCRI { get; set; }

    public decimal? CasualRecCalMCER { get; set; }

    public decimal? CasualRecCalMCEE { get; set; }

    public decimal? CasualRecActMCRI { get; set; }

    public decimal? CasualRecActMCER { get; set; }

    public decimal? CasualRecActMCEE { get; set; }

    public int? CostCenterID { get; set; }

    public int? PayRecID { get; set; }

    public DateTime? CasualRecSalaryDate { get; set; }

    public int? CasualRecDaysAdjusted { get; set; }
}