// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class CasualPlan
{
    public int CasualPlanID { get; set; }

    public string CasualPlanCode { get; set; }

    public string CasualPlanDesc { get; set; }

    public string CasualPlanTrusteeName { get; set; }

    public string CasualPlanSchemeNo { get; set; }

    public string CasualPlanCompanyName { get; set; }

    public string CasualPlanCompanyAddress { get; set; }

    public string CasualPlanContactName { get; set; }

    public string CasualPlanContactNo { get; set; }

    public int? CasualSchemeID { get; set; }

    public string CasualPlanParticipationNo { get; set; }

    public string CasualPlanExtendData { get; set; }

    public int? CasualPlanEmployerDecimalPlace { get; set; }

    public string CasualPlanEmployerRoundingRule { get; set; }

    public int? CasualPlanEmployeeDecimalPlace { get; set; }

    public string CasualPlanEmployeeRoundingRule { get; set; }
}