// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class CasualParameter
{
    public int CasualParamID { get; set; }

    public DateTime? CasualParamEffFr { get; set; }

    public DateTime? CasualParamEffTo { get; set; }

    public decimal? CasualParamMinDaily { get; set; }

    public decimal? CasualParamMaxDaily { get; set; }

    public decimal? CasualParamEEContribution { get; set; }

    public decimal? CasualParamERContribution { get; set; }
}