// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class CessationReason
{
    public int CessationReasonID { get; set; }

    public string CessationReasonCode { get; set; }

    public string CessationReasonDesc { get; set; }

    public int? CessationReasonIsSeverancePay { get; set; }

    public int? CessationReasonIsLongServicePay { get; set; }

    public int? CessationReasonHasProrataYEB { get; set; }

    public string eMPFTerminationCode { get; set; }

    public int? TaxCessationReason { get; set; }

    public string eMPFRemittanceStatementTerminationCode { get; set; }
}