// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class ClaimsAndDeductionsImportBatch
{
    public int CNDImportBatchID { get; set; }

    public DateTime? CNDImportBatchDateTime { get; set; }

    public int? CNDImportBatchUploadedBy { get; set; }

    public string CNDImportBatchRemark { get; set; }
}