// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class ClaimsAndDeduction
{
    public int CNDID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? CNDEffDate { get; set; }

    public int? PayCodeID { get; set; }

    public decimal? CNDAmount { get; set; }

    public string CurrencyID { get; set; }

    public string CNDPayMethod { get; set; }

    public int? EmpAccID { get; set; }

    public string CNDRemark { get; set; }

    public double? CNDNumOfDayAdj { get; set; }

    public int? PayRecID { get; set; }

    public int? EmpPayrollID { get; set; }

    public int? CNDImportBatchID { get; set; }

    public bool? CNDIsRestDayPayment { get; set; }

    public int? CostCenterID { get; set; }
}