// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class CommissionAchievementImportBatch
{
    public int CAImportBatchID { get; set; }

    public DateTime? CAImportBatchDateTime { get; set; }

    public int? CAImportBatchUploadedBy { get; set; }

    public string CAImportBatchRemark { get; set; }
}