// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class CommissionAchievement
{
    public int CAID { get; set; }

    public int? EmpID { get; set; }

    public decimal? CAPercent { get; set; }

    public int? RpID { get; set; }

    public int? CAImportBatchID { get; set; }

    public DateTime? CAEffDate { get; set; }
}