// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class CompanyBankAccountSetting
{
    public int SettingID { get; set; }

    public string AccountType { get; set; }

    public string ApcPlanCode { get; set; }

    public string ApcAccountType { get; set; }

    public string BankPaymentCode { get; set; }

    public string BatchDescription { get; set; }

    public string BatchName { get; set; }

    public string BatchID { get; set; }

    public string cboFileFormat { get; set; }

    public string CompanyBankAccountBankCode { get; set; }

    public string CompanyBankAccountAccountNo { get; set; }

    public string CompanyID { get; set; }

    public string ClientCode { get; set; }

    public string ClientIdentifier { get; set; }

    public string ChongHingCompanyCode { get; set; }

    public string CustomerReference { get; set; }

    public string DebitAccountCcy { get; set; }

    public string DebitAccountBranch { get; set; }

    public string DebtorReference { get; set; }

    public string DebtorReferenceForSBAutopay { get; set; }

    public string EFTKey { get; set; }

    public string ERCMGReference { get; set; }

    public string FileFormat { get; set; }

    public string FileFormats { get; set; }

    public string FileFormatList { get; set; }

    public string FirstPartyReference { get; set; }

    public string FileType { get; set; }

    public string FileVersionDropDown { get; set; }

    public string GroupID { get; set; }

    public string IFileConnectCustomerId { get; set; }

    public string IFileHSBCnetCustomerId { get; set; }

    public string IFileAccountType { get; set; }

    public string IFilePaymentCode { get; set; }

    public string IFileInstructionReference { get; set; }

    public bool? IncludeEmpNo { get; set; }

    public bool? IncludeMPFRecord { get; set; }

    public string Indicator { get; set; }

    public string mriPlanCode { get; set; }

    public string InstructionRemarks { get; set; }

    public string InvoiceDetails { get; set; }

    public bool? IsEncrypt { get; set; }

    public bool? IsFPSEncrypt { get; set; }

    public bool? IsSBEncrypt { get; set; }

    public bool? MAS { get; set; }

    public string MessageToBeneficiary { get; set; }

    public string MyProductCode { get; set; }

    public string multipleBankCode { get; set; }

    public string NotificationDetail { get; set; }

    public string OrderingPartyAddress1 { get; set; }

    public string OrderingPartyAddress2 { get; set; }

    public string OrderingPartyCityName { get; set; }

    public string OrganizationID { get; set; }

    public string Particulars { get; set; }

    public string Particular { get; set; }

    public string ParticularID { get; set; }

    public bool? PaylinkCheque { get; set; }

    public string ProductCode { get; set; }

    public string PaymentCode { get; set; }

    public string PaymentCodeSelection { get; set; }

    public string PaymentCustomerMemo { get; set; }

    public string PaymentCustomerReference { get; set; }

    public string PaymentProduct { get; set; }

    public string PaymentType { get; set; }

    public string PlanCode { get; set; }

    public string PrincipalReference { get; set; }

    public string Reference { get; set; }

    public string Remark { get; set; }

    public string SecondPartyReference { get; set; }

    public DateTime? SBValueDate { get; set; }

    public string SenderText1 { get; set; }

    public string SenderText2 { get; set; }

    public string SenderText3 { get; set; }

    public string SenderText4 { get; set; }

    public string SecurityGroup { get; set; }

    public string SubmissionPlatform { get; set; }

    public string Summary { get; set; }

    public string TransactionCode { get; set; }

    public string TransactionType { get; set; }

    public string TransactionReference { get; set; }

    public string txtPaymentDetails { get; set; }

    public string Type { get; set; }

    public bool? UseBIBFormat { get; set; }

    public string VelocityReference { get; set; }
}