// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class CompanyBankAccount
{
    public int CompanyBankAccountID { get; set; }

    public string CompanyBankAccountBankCode { get; set; }

    public string CompanyBankAccountBranchCode { get; set; }

    public string CompanyBankAccountAccountNo { get; set; }

    public string CompanyBankAccountHolderName { get; set; }

    public string CompanyBankAccountExtendData { get; set; }
}