// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class CompensationLeaveEntitle
{
    public int CompensationLeaveEntitleID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? CompensationLeaveEntitleEffectiveDate { get; set; }

    public DateTime? CompensationLeaveEntitleClaimPeriodFrom { get; set; }

    public DateTime? CompensationLeaveEntitleClaimPeriodTo { get; set; }

    public DateTime? CompensationLeaveEntitleClaimHourFrom { get; set; }

    public DateTime? CompensationLeaveEntitleClaimHourTo { get; set; }

    public double? CompensationLeaveEntitleDuration { get; set; }

    public string CompensationLeaveEntitleApprovedBy { get; set; }

    public string CompensationLeaveEntitleRemark { get; set; }

    public bool? CompensationLeaveEntitleIsAutoGenerated { get; set; }

    public DateTime? CompensationLeaveEntitleDateExpiry { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public bool? CompensationLeaveEntitleIsOTClaim { get; set; }

    public string CompensationLeaveEntitleUnit { get; set; }

    public int? OTClaimReasonID { get; set; }

    public int? CompensationLeaveEntitleOTClaimID { get; set; }

    public int? CompensationLeaveEntitleSupportingDocumentCount { get; set; }
}