// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class Company
{
    public int CompanyID { get; set; }

    public string CompanyCode { get; set; }

    public string CompanyName { get; set; }

    public string CompanyAddress { get; set; }

    public string CompanyContactPerson { get; set; }

    public string CompanyContactNo { get; set; }

    public string CompanyFaxNo { get; set; }

    public string CompanyBRNo { get; set; }

    public string CompanyBankCode { get; set; }

    public string CompanyBranchCode { get; set; }

    public string CompanyBankAccountNo { get; set; }

    public string CompanyBankHolderName { get; set; }

    public bool CompanyHasLeaveAttachement { get; set; }

    public string CompanyAttachmentCCList { get; set; }
}