// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class CostAllocationDetail
{
    public int CostAllocationDetailID { get; set; }

    public int? CostAllocationID { get; set; }

    public int? CompanyID { get; set; }

    public int? CostCenterID { get; set; }

    public int? PaymentCodeID { get; set; }

    public decimal? CostAllocationDetailAmount { get; set; }

    public int? PayRecID { get; set; }

    public int? CostAllocationDetailIsContribution { get; set; }
}