// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class CostAllocation
{
    public int CostAllocationID { get; set; }

    public int? EmpID { get; set; }

    public int? EmpPayrollID { get; set; }

    public string CostAllocationStatus { get; set; }

    public DateTime? CostAllocationTrialRunDate { get; set; }

    public int? CostAllocationTrialRunBy { get; set; }

    public DateTime? CostAllocationConfirmDate { get; set; }

    public int? CostAllocationConfirmBy { get; set; }
}