// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class CostAllocationDetailHElement
{
    public int CostAllocationDetailHElementID { get; set; }

    public int? CostAllocationDetailID { get; set; }

    public int? HElementID { get; set; }

    public int? HLevelID { get; set; }
}