// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class CostCenter
{
    public int CostCenterID { get; set; }

    public string CostCenterCode { get; set; }

    public string CostCenterDesc { get; set; }
}