// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class DocumentType
{
    public int DocumentTypeID { get; set; }

    public string DocumentTypeCode { get; set; }

    public string DocumentTypeDesc { get; set; }

    public bool? DocumentTypeIsSystem { get; set; }
}