// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class DoublePayAdjustmentImportBatch
{
    public int DoublePayAdjustImportBatchID { get; set; }

    public DateTime? DoublePayAdjustImportBatchDateTime { get; set; }

    public int? DoublePayAdjustImportBatchUploadedBy { get; set; }

    public string DoublePayAdjustImportBatchRemark { get; set; }
}