// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class DoublePayAdjustment
{
    public int DoublePayAdjustID { get; set; }

    public int? EmpID { get; set; }

    public int? RpID { get; set; }

    public decimal? SalesAchievementRate { get; set; }

    public int? DoublePayAdjustImportBatchID { get; set; }

    public DateTime? DoublePayAdjustEffDate { get; set; }
}