// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class eChannelMPFAuthorizedSignature
{
    public int eChannelMPFAuthorizedSignatureID { get; set; }

    public string Description { get; set; }

    public string EmployerID { get; set; }

    public string PayCenter { get; set; }

    public int? Checker1UserGroupID { get; set; }

    public string Checker1RoleLevel { get; set; }

    public double? Checker1MinAmount { get; set; }

    public int? Checker2UserGroupID { get; set; }

    public string Checker2RoleLevel { get; set; }

    public double? Checker2MinAmount { get; set; }
}