// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmailLog
{
    public int EmailLogID { get; set; }

    public string EmailLogToAddress { get; set; }

    public DateTime? EmailLogStartTime { get; set; }

    public DateTime? EmailLogEndTime { get; set; }

    public int? EmailLogTrialCount { get; set; }

    public bool? EmailLogIsFail { get; set; }

    public string EmailLogErrorMessage { get; set; }

    public string EmailSubject { get; set; }

    public string EmailBody { get; set; }
}