// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpAVCPlan
{
    public int EmpAVCID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpAVCEffFr { get; set; }

    public DateTime? EmpAVCEffTo { get; set; }

    public int? AVCPlanID { get; set; }

    public bool? EmpAVCEROverrideSetting { get; set; }

    public decimal? EmpAVCERBelowRI { get; set; }

    public decimal? EmpAVCERAboveRI { get; set; }

    public decimal? EmpAVCERFix { get; set; }

    public bool? EmpAVCEEOverrideSetting { get; set; }

    public decimal? EmpAVCEEBelowRI { get; set; }

    public decimal? EmpAVCEEAboveRI { get; set; }

    public decimal? EmpAVCEEFix { get; set; }

    public int? DefaultMPFPlanID { get; set; }

    public string EmpAVCPlanExtendData { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public DateTime? EmpCommencementDate { get; set; }
}