// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpAttendancePreparationProcess
{
    public int EmpAPPID { get; set; }

    public int EmpID { get; set; }

    public int? AttendancePreparationProcessID { get; set; }

    public int EmpRPID { get; set; }

    public string EmpPayFormulaType { get; set; }

    public string EmpPayFormulaCode { get; set; }

    public string Day1 { get; set; }

    public string Day2 { get; set; }

    public string Day3 { get; set; }

    public string Day4 { get; set; }

    public string Day5 { get; set; }

    public string Day6 { get; set; }

    public string Day7 { get; set; }

    public string Day8 { get; set; }

    public string Day9 { get; set; }

    public string Day10 { get; set; }

    public string Day11 { get; set; }

    public string Day12 { get; set; }

    public string Day13 { get; set; }

    public string Day14 { get; set; }

    public string Day15 { get; set; }

    public string Day16 { get; set; }

    public string Day17 { get; set; }

    public string Day18 { get; set; }

    public string Day19 { get; set; }

    public string Day20 { get; set; }

    public string Day21 { get; set; }

    public string Day22 { get; set; }

    public string Day23 { get; set; }

    public string Day24 { get; set; }

    public string Day25 { get; set; }

    public string Day26 { get; set; }

    public string Day27 { get; set; }

    public string Day28 { get; set; }

    public string Day29 { get; set; }

    public string Day30 { get; set; }

    public string Day31 { get; set; }

    public decimal? TotalHours { get; set; }

    public string EmployeeSignature { get; set; }

    public string Remarks { get; set; }

    public decimal BasicSalaryAmount { get; set; }

    public decimal AllowanceAmount { get; set; }

    public decimal TravelAllowanceAmount { get; set; }

    public decimal CurrentMonthDays { get; set; }

    public decimal HolidaysAndLeaveDays { get; set; }

    public decimal OtherFulLPayDays { get; set; }

    public decimal VoluntaryOTDays { get; set; }

    public decimal CasualLeaveDays { get; set; }

    public decimal SLAndMLDays { get; set; }

    public decimal NopaySLAndMlDays { get; set; }

    public decimal NoWorkDays { get; set; }

    public decimal TotalWorkAndLeaveDays { get; set; }

    public decimal TotalOTDays { get; set; }

    public decimal TotalOTAmount { get; set; }

    public decimal SLDays { get; set; }

    public decimal SLAmount { get; set; }

    public decimal ILDays { get; set; }

    public decimal ILAmount { get; set; }

    public decimal NoPayLeaveDays { get; set; }

    public decimal NoPayLeaveAmount { get; set; }

    public decimal PayLeaveDays { get; set; }

    public decimal PayLeaveAmount { get; set; }

    public decimal DeductOtherAmount { get; set; }

    public decimal DeductTimeCardAmount { get; set; }

    public decimal CompenAllowanceAmount { get; set; }

    public decimal CompenOthersAmount { get; set; }

    public decimal CompenTimeCardAmount { get; set; }

    public decimal OTAllowance1OTHours { get; set; }

    public decimal OTAllowance1HourlyWages { get; set; }

    public decimal OTAllowance1PayAmount { get; set; }

    public decimal OTAllowance1MinWages { get; set; }

    public decimal OTAllowance2OTHours { get; set; }

    public decimal OTAllowance2HourlyWages { get; set; }

    public decimal OTAllowance2PayAmount { get; set; }

    public decimal OTAllowance2MinWages { get; set; }

    public decimal OTPayAmountDiffMinWages { get; set; }

    public decimal? CNDAmount { get; set; }

    public int? APPImportBatchID { get; set; }

    public decimal? OtherAllowance1 { get; set; }

    public decimal? OtherAllowance2 { get; set; }

    public decimal? OtherAllowance3 { get; set; }

    public decimal? OtherAllowance4 { get; set; }

    public decimal? TotalAmount { get; set; }

    public DateTime? EmpJoinDate { get; set; }

    public DateTime? EmpTermDate { get; set; }

    public decimal? ShiftRI { get; set; }

    public decimal? MPFEECurrentMonth { get; set; }

    public decimal? MPFEELastMonth { get; set; }

    public decimal? MPFEELastLastMonth { get; set; }

    public decimal? MPFERCurrentMonth { get; set; }

    public decimal? MPFERLastMonth { get; set; }

    public decimal? MPFERLastLastMonth { get; set; }
}