// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpBonusProcess
{
    public int EmpBonusProcessID { get; set; }

    public int? EmpID { get; set; }

    public int? BonusProcessID { get; set; }

    public string EmpBonusProcessType { get; set; }

    public string EmpBonusProcessRank { get; set; }

    public decimal? EmpBonusProcessTargetSalary { get; set; }

    public decimal? EmpBonusProcessBonusProportion { get; set; }

    public decimal? EmpBonusProcessBonusAmount { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }
}