// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpBankAccount
{
    public int EmpBankAccountID { get; set; }

    public int? EmpID { get; set; }

    public string EmpBankCode { get; set; }

    public string EmpBranchCode { get; set; }

    public string EmpAccountNo { get; set; }

    public string EmpBankAccountHolderName { get; set; }

    public bool? EmpAccDefault { get; set; }

    public string EmpBankAccountRemark { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}