// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpBackpayInstruction
{
    public int EmpBPID { get; set; }

    public int? EmpID { get; set; }

    public int? EmpRPID { get; set; }

    public decimal? EmpBPOldAmount { get; set; }

    public decimal? EmpBPNewAmount { get; set; }

    public int? PayscaleMapID { get; set; }

    public DateTime? EmpBPPeriodFr { get; set; }

    public DateTime? EmpBPPeriodTo { get; set; }

    public string EmpBPSource { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }
}