// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpBenefit
{
    public int EmpBenefitID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpBenefitEffectiveDate { get; set; }

    public DateTime? EmpBenefitExpiryDate { get; set; }

    public int? EmpBenefitPlanID { get; set; }

    public decimal? EmpBenefitERPremium { get; set; }

    public decimal? EmpBenefitEEPremium { get; set; }

    public decimal? EmpBenefitSpousePremium { get; set; }

    public decimal? EmpBenefitChildPremium { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}