// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpCasualPlan
{
    public int EmpCasualID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpCasualEffFr { get; set; }

    public DateTime? EmpCasualEffTo { get; set; }

    public int? CasualPlanID { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}