// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpCostCenter
{
    public int EmpCostCenterID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpCostCenterEffFr { get; set; }

    public DateTime? EmpCostCenterEffTo { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}