// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpCostCenterDetail
{
    public int EmpCostCenterDetailID { get; set; }

    public int? EmpCostCenterID { get; set; }

    public int? CostCenterID { get; set; }

    public double? EmpCostCenterPercentage { get; set; }

    public int? EmpCostCenterDetailIsDefault { get; set; }
}