// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpContractTerm
{
    public int EmpContractID { get; set; }

    public int? EmpID { get; set; }

    public string EmpContractCompanyName { get; set; }

    public string EmpContractCompanyContactNo { get; set; }

    public string EmpContractCompanyAddr { get; set; }

    public DateTime? EmpContractEmployedFrom { get; set; }

    public DateTime? EmpContractEmployedTo { get; set; }

    public decimal? EmpContractGratuity { get; set; }

    public string CurrencyID { get; set; }

    public int? PayCodeID { get; set; }

    public string EmpContractGratuityMethod { get; set; }

    public int? EmpAccID { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}