// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpDisciplinary
{
    public int EmpDisciplinaryID { get; set; }

    public int EmpID { get; set; }

    public int? EmpDisciplinaryWarningID { get; set; }

    public DateTime? EmpDisciplinaryDate { get; set; }

    public string EmpDisciplinaryReason { get; set; }

    public string EmpDisciplinaryRemarks { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}