// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpDocument
{
    public int EmpDocumentID { get; set; }

    public int? EmpID { get; set; }

    public int? DocumentTypeID { get; set; }

    public string EmpDocumentOriginalFileName { get; set; }

    public string EmpDocumentDesc { get; set; }

    public string EmpDocumentStoredFileName { get; set; }

    public bool? EmpDocumentIsCompressed { get; set; }

    public bool? EmpDocumentIsProfilePhoto { get; set; }
}