// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpESSDelegate
{
    public int EmpESSDelegateID { get; set; }

    public int? AppointerEmpID { get; set; }

    public int? AppointeeEmpID { get; set; }

    public int? ESSDelegateFuncID { get; set; }

    public DateTime? EffectiveDateTime { get; set; }

    public DateTime? ExpiryDateTime { get; set; }

    public bool? DelegateIsActive { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }
}