// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpExtraField
{
    public int EmpExtraFieldID { get; set; }

    public string EmpExtraFieldName { get; set; }

    public string EmpExtraFieldControlType { get; set; }

    public string EmpExtraFieldGroupName { get; set; }
}