// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpEmergencyContact
{
    public int EmpEmergencyContactID { get; set; }

    public int? EmpID { get; set; }

    public string EmpEmergencyContactName { get; set; }

    public string EmpEmergencyContactGender { get; set; }

    public string EmpEmergencyContactRelationship { get; set; }

    public string EmpEmergencyContactContactNo { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}