// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpESSActForHistory
{
    public int EmpESSActForHistoryID { get; set; }

    public int? EmpID { get; set; }

    public int? ActingForEmpID { get; set; }

    public DateTime? StartDateTime { get; set; }

    public DateTime? EndDateTime { get; set; }
}