// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpFormDatum
{
    public int EmpFormDataID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EeSignDateTime { get; set; }

    public DateTime? ErSignDateTime { get; set; }

    public DateTime? EeSubmitDateTime { get; set; }

    public DateTime? ErReviewDateTime { get; set; }

    public DateTime? ErSubmitDateTime { get; set; }

    public DateTime? ToHSBCDateTime { get; set; }

    public DateTime? CancelledDateTime { get; set; }

    public DateTime? FormDueDate { get; set; }

    public string FormType { get; set; }

    public int? EmpFormBodyID { get; set; }

    public string Status { get; set; }

    public int? TokenID { get; set; }

    public int? EmpMPFPlanID { get; set; }

    public int? EmpDocumentID { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SubmissionSource { get; set; }

    public DateTime? PreAgreementReadDateTime { get; set; }

    public bool? IsErSectionConfirmed { get; set; }

    public int? ErSubmittedBy { get; set; }
}