// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpFinalPayment
{
    public int EmpFinalPayID { get; set; }

    public int? EmpID { get; set; }

    public int? PayCodeID { get; set; }

    public decimal? EmpFinalPayAmount { get; set; }

    public string CurrencyID { get; set; }

    public string EmpFinalPayMethod { get; set; }

    public int? EmpAccID { get; set; }

    public bool? EmpFinalPayIsAutoGen { get; set; }

    public double? EmpFinalPayNumOfDayAdj { get; set; }

    public int? LeaveAppID { get; set; }

    public int? PayRecID { get; set; }

    public string EmpFinalPayRemark { get; set; }

    public string LeaveAppIDList { get; set; }

    public bool? EmpFinalPayIsRestDayPayment { get; set; }

    public int? CostCenterID { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}