// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpFormBody
{
    public int EmpFormBodyID { get; set; }

    public string FormName { get; set; }

    public string FormBodyJson { get; set; }

    public string ErInfoJson { get; set; }

    public byte[] ErSignature { get; set; }

    public byte[] EeSignature { get; set; }
}