// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpLeaveCashOut
{
    public int EmpCashOutID { get; set; }

    public int? CashOutProcessID { get; set; }

    public int? EmpID { get; set; }

    public int? EmpCashOutLeaveCodeID { get; set; }

    public float? EmpCashOutBalanceImageBF { get; set; }

    public float? EmpCashOutBalanceImageExpired { get; set; }

    public float? EmpCashOutBalanceImageForfeit { get; set; }

    public float? EmpCashOutBalanceImageAdjust { get; set; }

    public float? EmpCashOutBalanceImageEntitle { get; set; }

    public float? EmpCashOutBalanceImageTaken { get; set; }

    public float? EmpCashOutBalanceImageReserved { get; set; }

    public float? EmpCashOutBalanceImageBalance { get; set; }

    public float? EmpCashOutBalanceCashOut { get; set; }

    public string EmpCashOutRemark { get; set; }

    public float? EmpCashOutBalanceMaxCF { get; set; }
}