// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmploymentType
{
    public int EmploymentTypeID { get; set; }

    public string EmploymentTypeCode { get; set; }

    public string EmploymentTypeDesc { get; set; }
}