// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpMPFPlan
{
    public int EmpMPFID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpMPFEffFr { get; set; }

    public DateTime? EmpMPFEffTo { get; set; }

    public int? MPFPlanID { get; set; }

    public string EmpMPFPlanExtendData { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public bool? EmpMPFPlanEnrollmentFormAllowed { get; set; }

    public string eMPFGradeOrRank { get; set; }

    public string EmpMPFPlanEmployeeType { get; set; }

    public DateTime? EmpMPFPlanPreviousEmploymentDate { get; set; }

    public DateTime? EmpMPFPlanVisaIssueDate { get; set; }

    public string EmpMPFPlanMemberAccount { get; set; }

    public string EmpMPFPlanDefaultMemberClass { get; set; }

    public DateTime? EmpMPFPlanSchemeTransferDate { get; set; }
}