// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpOverseasCompany
{
    public int ID { get; set; }

    public int EmpID { get; set; }

    public int IsPaidBy { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }
}