// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpORSOPlan
{
    public int EmpORSOID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpORSOEffFr { get; set; }

    public DateTime? EmpORSOEffTo { get; set; }

    public int? ORSOPlanID { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}