// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpPayslip
{
    public int EmpPayslipID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpPayslipValueDate { get; set; }

    public DateTime? EmpPayslipPeriodStartDate { get; set; }

    public DateTime? EmpPayslipPeriodEndDate { get; set; }

    public string EmpPayslipFilename { get; set; }

    public decimal? EmpPayslipAmount { get; set; }

    public bool? EmpPayslipIsLocked { get; set; }

    public int? EmpPayrollID { get; set; }
}