// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpPayroll
{
    public int EmpPayrollID { get; set; }

    public int? PayPeriodID { get; set; }

    public int? EmpID { get; set; }

    public string EmpPayStatus { get; set; }

    public int? PayBatchID { get; set; }

    public string EmpPayIsRP { get; set; }

    public string EmpPayIsCND { get; set; }

    public string EmpPayIsYEB { get; set; }

    public string EmpPayIsHistoryAdj { get; set; }

    public DateTime? EmpPayTrialRunDate { get; set; }

    public int? EmpPayTrialRunBy { get; set; }

    public DateTime? EmpPayConfirmDate { get; set; }

    public int? EmpPayConfirmBy { get; set; }

    public double? EmpPayNumOfDayCount { get; set; }

    public DateTime? EmpPayValueDate { get; set; }

    public double? EmpPayTotalWorkingHours { get; set; }

    public string EmpPayIsAdditionalRemuneration { get; set; }

    public string EmpPayRemark { get; set; }
}