// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpPermit
{
    public int EmpPermitID { get; set; }

    public int? EmpID { get; set; }

    public int? PermitTypeID { get; set; }

    public string EmpPermitNo { get; set; }

    public DateTime? EmpPermitIssueDate { get; set; }

    public DateTime? EmpPermitExpiryDate { get; set; }

    public string EmpPermitRemark { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}