// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpRequestApprovalHistory
{
    public int EmpRequestApprovalHistoryID { get; set; }

    public int? EmpRequestID { get; set; }

    public string EmpRequestApprovalHistoryStatusBefore { get; set; }

    public int? EmpRequestApprovalHistoryAuthorizationWorkFlowIndexBefore { get; set; }

    public string EmpRequestApprovalHistoryStatusAfter { get; set; }

    public int? EmpRequestApprovalHistoryAuthorizationWorkFlowIndexAfter { get; set; }

    public string EmpRequestApprovalHistoryActionBy { get; set; }

    public int? EmpRequestApprovalHistoryActionByEmpID { get; set; }

    public DateTime? EmpRequestApprovalHistoryCreateDateTime { get; set; }

    public string EmpRequestApprovalHistoryRemark { get; set; }

    public int? EmpRequestApprovalHistoryDelegateEmpID { get; set; }
}