// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpRosterTableGroup
{
    public int EmpRosterTableGroupID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpRosterTableGroupEffFr { get; set; }

    public DateTime? EmpRosterTableGroupEffTo { get; set; }

    public int? RosterTableGroupID { get; set; }

    public bool? EmpRosterTableGroupIsSupervisor { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public bool? EmpRosterTableGroupIsShareable { get; set; }
}