// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpRequest
{
    public int EmpRequestID { get; set; }

    public int? EmpID { get; set; }

    public string EmpRequestType { get; set; }

    public int? EmpRequestRecordID { get; set; }

    public DateTime? EmpRequestCreateDate { get; set; }

    public DateTime? EmpRequestModifyDate { get; set; }

    public string EmpRequestStatus { get; set; }

    public int? EmpRequestLastAuthorizationWorkFlowIndex { get; set; }

    public string EmpRequestLastActionBy { get; set; }

    public int? EmpRequestLastActionByEmpID { get; set; }

    public int? AuthorizationWorkFlowID { get; set; }

    public DateTime? EmpRequestFromDate { get; set; }

    public DateTime? EmpRequestToDate { get; set; }
}