// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpSpouse
{
    public int EmpSpouseID { get; set; }

    public int? EmpID { get; set; }

    public string EmpSpouseSurname { get; set; }

    public string EmpSpouseOtherName { get; set; }

    public string EmpSpouseChineseName { get; set; }

    public string EmpSpouseHKID { get; set; }

    public string EmpSpousePassportNo { get; set; }

    public string EmpSpousePassportIssuedCountry { get; set; }

    public DateTime? EmpSpouseDateOfBirth { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public string EmpGender { get; set; }

    public bool? EmpIsMedicalSchemaInsured { get; set; }

    public DateTime? EmpMedicalEffectiveDate { get; set; }

    public DateTime? EmpMedicalExpiryDate { get; set; }

    public int? PassportIssuedCountryID { get; set; }
}