// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpSearch
{
    public int EmpSearchID { get; set; }

    public string EmpSearchKeyword { get; set; }

    public int? EmpSearchOption { get; set; }

    public int? EmpID { get; set; }
}