// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpTaxReport
{
    public int EmpTaxReportID { get; set; }

    public int? EmpID { get; set; }

    public int? TaxEmpID { get; set; }

    public string EmpTaxReportFilename { get; set; }
}