// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpTrainingEnroll
{
    public int EmpTrainingEnrollID { get; set; }

    public int? EmpID { get; set; }

    public int? TrainingSeminarID { get; set; }
}