// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpTermination
{
    public int EmpTerminationID { get; set; }

    public int? EmpID { get; set; }

    public int? CessationReasonID { get; set; }

    public DateTime? EmpTermResignDate { get; set; }

    public int? EmpTermNoticePeriod { get; set; }

    public string EmpTermNoticeUnit { get; set; }

    public DateTime? EmpTermLastDate { get; set; }

    public string EmpTermRemark { get; set; }

    public bool? EmpTermIsTransferCompany { get; set; }

    public int? NewEmpID { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}