// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpTrainingProgram
{
    public int EmpProgramID { get; set; }

    public int EmpID { get; set; }

    public string ProgramType { get; set; }

    public int ProgramID { get; set; }

    public string ProgramName { get; set; }

    public int? InstitutionID { get; set; }

    public string InstitutionName { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int? NoOfSession { get; set; }

    public int? VenueID { get; set; }

    public int? QualificationID { get; set; }

    public DateTime? DateOfQualification { get; set; }

    public int? TrainerID { get; set; }

    public decimal Cost { get; set; }

    public int? EmpSponsorshipID { get; set; }

    public decimal? AmountOfSponsorship { get; set; }

    public decimal? SponsorshipBalance { get; set; }

    public decimal? Sponsorship { get; set; }

    public int? Refund { get; set; }

    public DateTime? DateOfRefund { get; set; }

    public decimal? RefundAmount { get; set; }

    public decimal? TotalRefundAmount { get; set; }

    public int? ServiceBond { get; set; }

    public DateTime? ServiceBondEndDate { get; set; }

    public string Remark { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public decimal? TrainingHours { get; set; }

    public decimal? InternalProgramCost { get; set; }

    public int? CategoryID { get; set; }

    public int? SubCategoryID { get; set; }

    public string Speaker { get; set; }
}