// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpUniform
{
    public int EmpUniformID { get; set; }

    public int? EmpID { get; set; }

    public string EmpUniformB { get; set; }

    public string EmpUniformW { get; set; }

    public string EmpUniformH { get; set; }
}