// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class EmpWorkInjuryRecord
{
    public int EmpWorkInjuryRecordID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpWorkInjuryRecordAccidentDate { get; set; }

    public string EmpWorkInjuryRecordAccidentLocation { get; set; }

    public string EmpWorkInjuryRecordAccidentReason { get; set; }

    public string EmpWorkInjuryRecordInjuryNature { get; set; }

    public DateTime? EmpWorkInjuryRecordReportedDate { get; set; }

    public DateTime? EmpWorkInjuryRecordChequeReceivedDate { get; set; }

    public DateTime? EmpWorkInjuryRecordSettleDate { get; set; }

    public string EmpWorkInjuryRecordRemark { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}