// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class EmpWorkingSummary
{
    public int EmpWorkingSummaryID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpWorkingSummaryAsOfDate { get; set; }

    public double? EmpWorkingSummaryRestDayEntitled { get; set; }

    public double? EmpWorkingSummaryRestDayTaken { get; set; }

    public double? EmpWorkingSummaryTotalWorkingDays { get; set; }

    public double? EmpWorkingSummaryTotalWorkingHours { get; set; }

    public double? EmpWorkingSummaryTotalLunchTimeHours { get; set; }

    public double? EmpWorkingSummaryTotalStatutoryHoliday { get; set; }

    public double? EmpWorkingSummaryTotalLeaveDaysTaken { get; set; }

    public double? EmpWorkingSummaryExpectedTotalWorkingHours { get; set; }

    public double? EmpWorkingSummaryTotalOvertimeMinutes { get; set; }

    public double? EmpWorkingSummaryTotalLateMinutes { get; set; }

    public double? EmpWorkingSummaryTotalEarlyLeaveMinutes { get; set; }
}