// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class ERosterCSVLog
{
    public int LogID { get; set; }

    public DateTime? CallDateTime { get; set; }

    public DateTime? FromDate { get; set; }

    public bool? IsFullExport { get; set; }
}