// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class ESSAnnouncement
{
    public int ESSAnnouncementID { get; set; }

    public string ESSAnnouncementCode { get; set; }

    public DateTime? ESSAnnouncementEffectiveDate { get; set; }

    public DateTime? ESSAnnouncementExpiryDate { get; set; }

    public string ESSAnnouncementContent { get; set; }

    public string ESSAnnouncementTargetCompanies { get; set; }

    public string ESSAnnouncementTargetRanks { get; set; }

    public bool? ForceToRead { get; set; }
}