// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class ESSDelegateFunc
{
    public int ESSDelegateFuncID { get; set; }

    public string FuncCode { get; set; }

    public string Desc { get; set; }

    public string CDesc { get; set; }
}