// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class ESSLoginAudit
{
    public int ESSLoginAuditID { get; set; }

    public int? EmpID { get; set; }

    public string ESSLoginAuditLoginID { get; set; }

    public string ESSLoginAuditLoginMachine { get; set; }

    public string ESSLoginAuditLoginIPAddress { get; set; }

    public string ESSLoginAuditLoginAgent { get; set; }

    public DateTime? ESSLoginAuditLoginDateTime { get; set; }

    public bool? ESSLoginAuditIsLoginFail { get; set; }

    public string ESSLoginAuditLoginErrorMesage { get; set; }
}