// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class ESSPasswordHistory
{
    public int ESSPasswordHistoryID { get; set; }

    public int? EmpID { get; set; }

    public string ESSPasswordHistoryPassword { get; set; }

    public DateTime? ESSPasswordHistoryEffectiveDate { get; set; }
}