// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class HierarchyLevel
{
    public int HLevelID { get; set; }

    public string HLevelCode { get; set; }

    public string HLevelDesc { get; set; }

    public int? HLevelSeqNo { get; set; }

    public string HLevelCDesc { get; set; }
}