// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class HierarchyElement
{
    public int HElementID { get; set; }

    public int? CompanyID { get; set; }

    public string HElementCode { get; set; }

    public string HElementDesc { get; set; }

    public int? HLevelID { get; set; }

    public string RegistrationSource { get; set; }

    public string RegistrationSourceID { get; set; }
}