// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class HitRateProcessImportBatch
{
    public int HitRateProcessImportBatchID { get; set; }

    public DateTime? HitRateProcessImportBatchDateTime { get; set; }

    public int? HitRateProcessImportBatchUploadedBy { get; set; }

    public string HitRateProcessImportBatchRemark { get; set; }
}