// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class HitRateProcess
{
    public int HitRateProcessID { get; set; }

    public int? EmpID { get; set; }

    public int? RpID { get; set; }

    public int? payCodeID { get; set; }

    public decimal? HitRate { get; set; }

    public int? HitRateProcessImportBatchID { get; set; }
}