// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class HROneApiLog
{
    public long LogID { get; set; }

    public DateTime Timestamp { get; set; }

    public string Endpoint { get; set; }

    public string RequestMethod { get; set; }

    public string RequestBody { get; set; }

    public int ResponseCode { get; set; }

    public string ResponseBody { get; set; }

    public string UserID { get; set; }

    public string ClientIP { get; set; }

    public bool Success { get; set; }

    public string ErrorMessage { get; set; }

    public int? ProcessingTimeMs { get; set; }

    public string Remarks { get; set; }

    public string SessionID { get; set; }

    public int? CompanyID { get; set; }

    public string RequestHash { get; set; }

    public int? RequestSize { get; set; }

    public int? ResponseSize { get; set; }

    public string CreatedBy { get; set; }
}