// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class INBOX
{
    public int InboxID { get; set; }

    public int? UserID { get; set; }

    public int? InboxFromUserID { get; set; }

    public string InboxFromUserName { get; set; }

    public string InboxType { get; set; }

    public string InboxSubject { get; set; }

    public int? EmpID { get; set; }

    public int? InboxRelatedRecID { get; set; }

    public DateTime? InboxRelatedReferenceDate { get; set; }

    public string InboxMessage { get; set; }

    public DateTime? InboxCreateDate { get; set; }

    public DateTime? InboxReadDate { get; set; }

    public DateTime? InboxDeleteDate { get; set; }
}