// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class InboxAttachment
{
    public int InboxAttachmentID { get; set; }

    public int? InboxID { get; set; }

    public string InboxAttachmentOriginalFileName { get; set; }

    public string InboxAttachmentStoredFileName { get; set; }

    public int? InboxAttachmentIsCompressed { get; set; }

    public long? InboxAttachmentSize { get; set; }
}