// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class IncentivePayment
{
    public int IPID { get; set; }

    public int? EmpID { get; set; }

    public decimal? IPPercent { get; set; }

    public int? RpID { get; set; }

    public int? IPImportBatchID { get; set; }

    public DateTime? IPEffDate { get; set; }
}