// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class IncentivePaymentImportBatch
{
    public int IPImportBatchID { get; set; }

    public DateTime? IPImportBatchDateTime { get; set; }

    public int? IPImportBatchUploadedBy { get; set; }

    public string IPImportBatchRemark { get; set; }
}