// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class Institution
{
    public int InstitutionID { get; set; }

    public string InstitutionCode { get; set; }

    public string InstitutionName { get; set; }
}