// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class IssueCountry
{
    public int CountryID { get; set; }

    public string CountryCode { get; set; }

    public string CountryDesc { get; set; }
}