// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class LateWaive
{
    public int LateWaiveID { get; set; }

    public int? EmpID { get; set; }

    public int? AttendanceRecordID { get; set; }

    public string LateWaiveReason { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public int? LateWaiveCancelID { get; set; }

    public int? EmpRequestID { get; set; }

    public int? RequestLateWaiveID { get; set; }

    public string SynID { get; set; }
}