// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class LAWS_IN_OUT_REMARK
{
    public int attendanceRecordRemarkID { get; set; }

    public int EmpID { get; set; }

    public DateTime? attendanceRecordRemarkDate { get; set; }

    public string attendanceRecordRemarkRemark { get; set; }

    public DateTime? attendanceRecordRemarkCreateDate { get; set; }
}