// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class LeavePlanBroughtForward
{
    public int LeavePlanBroughtForwardID { get; set; }

    public int? LeavePlanID { get; set; }

    public int? LeaveTypeID { get; set; }

    public int? LeavePlanBroughtForwardMax { get; set; }

    public bool? LeavePlanBroughtForwardForfeitLastYearBroughtForwardOnly { get; set; }

    public int? LeavePlanBroughtForwardNumOfMonthExpired { get; set; }
}