// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class LeaveApplicationDeleted
{
    public int LeaveAppID { get; set; }

    public int? EmpID { get; set; }

    public int? LeaveCodeID { get; set; }

    public string LeaveAppUnit { get; set; }

    public DateTime? LeaveAppDateFrom { get; set; }

    public DateTime? LeaveAppDateTo { get; set; }

    public DateTime? LeaveAppTimeFrom { get; set; }

    public DateTime? LeaveAppTimeTo { get; set; }

    public decimal? LeaveAppDays { get; set; }

    public int? LeaveAppHasMedicalCertificate { get; set; }

    public int? LeaveAppNoPayProcess { get; set; }

    public int? EmpPaymentID { get; set; }

    public int? EmpPayrollID { get; set; }

    public double? LeaveAppHours { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public int? LeaveAppCancelID { get; set; }

    public int? EmpRequestID { get; set; }

    public int? RequestLeaveAppID { get; set; }

    public string SynID { get; set; }

    public string LeaveAppDateFromAM { get; set; }

    public string LeaveAppDateToAM { get; set; }

    public DateTime? RecordDeletedDateTime { get; set; }
}