// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class LeavePlanEntitle
{
    public int LeavePlanEntitleID { get; set; }

    public int? LeavePlanID { get; set; }

    public int? LeaveTypeID { get; set; }

    public int? LeavePlanEntitleYearOfService { get; set; }

    public double? LeavePlanEntitleDays { get; set; }

    public int? LeavePlanBroughtForwardMax { get; set; }
}