// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class LeaveApplicationCancel
{
    public int LeaveAppCancelID { get; set; }

    public int? EmpID { get; set; }

    public int? LeaveAppID { get; set; }

    public DateTime? LeaveAppCancelCreateDateTime { get; set; }

    public string LeaveAppCancelReason { get; set; }

    public int? EmpRequestID { get; set; }

    public int? RequestLeaveAppCancelID { get; set; }
}