// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class LeaveBalanceAdjustment
{
    public int LeaveBalAdjID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? LeaveBalAdjDate { get; set; }

    public int? LeaveTypeID { get; set; }

    public string LeaveBalAdjType { get; set; }

    public double? LeaveBalAdjValue { get; set; }

    public string LeaveBalAdjRemark { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public string LeaveBalAdjUnit { get; set; }
}