// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class LeaveType
{
    public int LeaveTypeID { get; set; }

    public string LeaveType1 { get; set; }

    public string LeaveTypeDesc { get; set; }

    public int? LeaveDecimalPlace { get; set; }

    public int? LeaveSystemUse { get; set; }

    public bool? LeaveTypeIsUseWorkHourPattern { get; set; }

    public bool? LeaveTypeIsSkipStatutoryHolidayChecking { get; set; }

    public bool? LeaveTypeIsSkipPublicHolidayChecking { get; set; }

    public bool? LeaveTypeIsESSHideLeaveBalance { get; set; }

    public bool? LeaveTypeIsESSRestrictNegativeBalanceAsOfToday { get; set; }

    public bool? LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom { get; set; }

    public bool? LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo { get; set; }

    public bool? LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear { get; set; }

    public bool? LeaveTypeIsDisabled { get; set; }

    public bool? LeaveTypeIsESSIgnoreEntitlement { get; set; }

    public decimal? LeaveTypeIsESSAllowableAdvanceBalance { get; set; }

    public bool? LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveMonth { get; set; }

    public bool? LeaveBalanceShowInPayslip { get; set; }

    public string LeaveTypeColor { get; set; }

    public string CurrentEntitlementEligibleBeforeAfter { get; set; }

    public DateTime? CurrentEntitlementEligibleJoinDate { get; set; }

    public bool? LeaveTypeIsESSRestrictEarlierThanSpecified { get; set; }

    public int? LeaveTypeIsESSRestrictEarlierThanDays { get; set; }

    public bool? LeaveTypeIsESSRestrictLaterThanSpecified { get; set; }

    public int? LeaveTypeIsESSRestrictLaterThanDays { get; set; }

    public bool? LeaveTypeERosterIsDisplay { get; set; }

    public string LeaveTypeERosterDisplayCode { get; set; }
}