// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class LeaveBalanceEntitle
{
    public int LeaveBalanceEntitleID { get; set; }

    public int? EmpID { get; set; }

    public int? LeaveTypeID { get; set; }

    public DateTime? LeaveBalanceEntitleEffectiveDate { get; set; }

    public DateTime? LeaveBalanceEntitleDateExpiry { get; set; }

    public double? LeaveBalanceEntitleDays { get; set; }

    public DateTime? LeaveBalanceEntitleGrantPeriodFrom { get; set; }

    public DateTime? LeaveBalanceEntitleGrantPeriodTo { get; set; }
}