// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class LeaveBalance
{
    public int LeaveBalanceID { get; set; }

    public int? EmpID { get; set; }

    public int? LeaveTypeID { get; set; }

    public DateTime? LeaveBalanceEffectiveDate { get; set; }

    public double? LeaveBalanceBF { get; set; }

    public double? LeaveBalanceForfeiture { get; set; }

    public double? LeaveBalanceEntitled { get; set; }

    public int? LeaveBalancePeriod { get; set; }

    public bool? LeaveBalanceIsSettlement { get; set; }

    public bool? LeaveBalanceIsFirst { get; set; }
}