// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class LeaveCashOutProcess
{
    public int CashOutProcessID { get; set; }

    public DateTime? CashOutProcessMonth { get; set; }

    public string CashOutProcessDesc { get; set; }

    public string CashOutProcessStatus { get; set; }

    public DateTime? CashOutProcessPayDate { get; set; }

    public int? CashOutProcessEmpCount { get; set; }

    public int? CashOutProcessLeaveTypeID { get; set; }

    public int? CashOutProcessPercentForCashOut { get; set; }

    public DateTime? CashOutProcessBalanceAsAtDate { get; set; }

    public int? CashOutProcessPayFormulaID { get; set; }

    public int? CashOutProcessPayCodeID { get; set; }

    public string CashOutProcessRemark { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }
}