// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class LeavePlan
{
    public int LeavePlanID { get; set; }

    public string LeavePlanCode { get; set; }

    public string LeavePlanDesc { get; set; }

    public int? ALProrataRoundingRuleID { get; set; }

    public bool? LeavePlanResetYearOfService { get; set; }

    public bool? LeavePlanNoCountFirstIncompleteYearOfService { get; set; }

    public bool? LeavePlanComparePreviousLeavePlan { get; set; }

    public int? LeavePlanLeavePlanCompareRank { get; set; }

    public bool? LeavePlanProrataSkipFeb29 { get; set; }

    public bool? LeavePlanUseStatutoryHolidayEntitle { get; set; }

    public bool? LeavePlanUseRestDayEntitle { get; set; }

    public string LeavePlanRestDayEntitlePeriod { get; set; }

    public double? LeavePlanRestDayEntitleDays { get; set; }

    public string LeavePlanRestDayWeeklyEntitleStartDay { get; set; }

    public double? LeavePlanRestDayMonthlyEntitleProrataBase { get; set; }

    public int? LeavePlanRestDayMonthlyEntitleProrataRoundingRuleID { get; set; }

    public bool? LeavePlanALRoundingRuleIsApplyFirstYearBroughtForwardOnly { get; set; }

    public bool? LeavePlanUseCommonLeaveYear { get; set; }

    public int? LeavePlanCommonLeaveYearStartMonth { get; set; }

    public int? LeavePlanCommonLeaveYearStartDay { get; set; }

    public bool? LeavePlanUsePublicHolidayEntitle { get; set; }

    public bool? LeavePlanUseAnnualLeave1stEntitlementExtension { get; set; }

    public int? LeavePlanAnnualLeave1stEntitlementExtendedServiceStartedFrom { get; set; }

    public int? LeavePlanAnnualLeave1stEntitlementExtendedServiceStartedTo { get; set; }

    public int? LeavePlanAnnualLeave1stEntitlementExtendedNoOfMonth { get; set; }
}