// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class LeaveCode
{
    public int LeaveCodeID { get; set; }

    public string LeaveCode1 { get; set; }

    public string LeaveCodeDesc { get; set; }

    public int? LeaveTypeID { get; set; }

    public decimal? LeaveCodePayRatio { get; set; }

    public int? LeaveCodeLeaveAllowPaymentCodeID { get; set; }

    public int? LeaveCodeLeaveDeductPaymentCodeID { get; set; }

    public int? LeaveCodeLeaveDeductFormula { get; set; }

    public int? LeaveCodeLeaveAllowFormula { get; set; }

    public bool? LeaveCodePayAdvance { get; set; }

    public int? PaymentCodeID { get; set; }

    public bool? LeaveCodeHideInESS { get; set; }

    public bool? LeaveCodeIsSkipPayrollProcess { get; set; }

    public bool? LeaveCodeIsPayrollProcessNextMonth { get; set; }

    public bool? LeaveCodeUseAllowancePaymentCodeIfSameAmount { get; set; }

    public bool? LeaveCodeIsCNDProrata { get; set; }

    public bool? LeaveCodeIsShowMedicalCertOption { get; set; }

    public string LeaveAppUnit { get; set; }

    public bool? LeaveCodeAppUnitDay { get; set; }

    public bool? LeaveCodeAppUnitAM { get; set; }

    public bool? LeaveCodeAppUnitPM { get; set; }

    public bool? LeaveCodeAppUnitHour { get; set; }

    public bool? LeaveCodeShowOnMale { get; set; }

    public bool? LeaveCodeShowOnFemale { get; set; }

    public int? LeaveCodeShowOnWorkPeriodDuration { get; set; }

    public string LeaveCodeShowOnWorkPeriodUnit { get; set; }

    public bool? LeaveCodeShowOnInProbation { get; set; }

    public bool? LeaveCodeShowOnAfterProbation { get; set; }

    public string LeaveCodeShowOnMaritalStatus { get; set; }

    public string LeaveCodeRelevantCertReminder { get; set; }

    public bool? LeaveCodeRelevantCertImageIsMandatory { get; set; }

    public bool? LeaveCodeExcludeDAWDaysAdjusted { get; set; }

    public bool? LeaveCodeERosterIsDisplay { get; set; }
}