// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class LoginAudit
{
    public int LoginAuditID { get; set; }

    public int? UserID { get; set; }

    public string LoginAuditLoginID { get; set; }

    public string LoginAuditLoginMachine { get; set; }

    public string LoginAuditLoginIPAddress { get; set; }

    public string LoginAuditLoginAgent { get; set; }

    public DateTime? LoginAuditLoginDateTime { get; set; }

    public bool? LoginAuditIsLoginFail { get; set; }

    public string LoginAuditLoginErrorMesage { get; set; }
}