// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class MinimumWage
{
    public int MinimumWageID { get; set; }

    public DateTime? MinimumWageEffectiveDate { get; set; }

    public double? MinimumWageHourlyRate { get; set; }
}