// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class MPFPlan
{
    public int MPFPlanID { get; set; }

    public string MPFPlanCode { get; set; }

    public string MPFPlanDesc { get; set; }

    public string MPFPlanTrusteeName { get; set; }

    public string MPFPlanSchemeNo { get; set; }

    public string MPFPlanCompanyName { get; set; }

    public string MPFPlanCompanyAddress { get; set; }

    public string MPFPlanContactName { get; set; }

    public string MPFPlanContactNo { get; set; }

    public int? MPFSchemeID { get; set; }

    public string MPFPlanParticipationNo { get; set; }

    public string MPFPlanExtendData { get; set; }

    public int? MPFPlanEmployerDecimalPlace { get; set; }

    public string MPFPlanEmployerRoundingRule { get; set; }

    public int? MPFPlanEmployeeDecimalPlace { get; set; }

    public string MPFPlanEmployeeRoundingRule { get; set; }

    public int? MPFPlanOverrideCostCenterID { get; set; }

    public int? MPFPlanParentPlanID { get; set; }

    public string MPFPlanEnrollmentErSignMethod { get; set; }

    public string ErSignerName { get; set; }

    public string m_ErSignerMobileNo { get; set; }

    public string ErSignerMobileNo { get; set; }

    public bool? SwitchFundConfirmationIsEnabled { get; set; }

    public bool? EEInitMPFEnrollmentFormIsEnabled { get; set; }

    public string eMPFGradeOrRank { get; set; }

    public string eMPFerAccNo { get; set; }

    public string eMPFpayrollGroupId { get; set; }

    public string eMPFdepartCode { get; set; }

    public string eMPFMemberClass { get; set; }
}