// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class MPFParameter
{
    public int MPFParamID { get; set; }

    public DateTime? MPFParamEffFr { get; set; }

    public decimal? MPFParamMinMonthly { get; set; }

    public decimal? MPFParamMaxMonthly { get; set; }

    public decimal? MPFParamMinDaily { get; set; }

    public decimal? MPFParamMaxDaily { get; set; }

    public decimal? MPFParamEEPercent { get; set; }

    public decimal? MPFParamERPercent { get; set; }
}