// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class MPFRecord
{
    public int MPFRecordID { get; set; }

    public int EmpPayrollID { get; set; }

    public int MPFPlanID { get; set; }

    public int AVCPlanID { get; set; }

    public DateTime MPFRecPeriodFr { get; set; }

    public DateTime MPFRecPeriodTo { get; set; }

    public string MPFRecType { get; set; }

    public decimal? MPFRecCalMCRI { get; set; }

    public decimal? MPFRecCalMCER { get; set; }

    public decimal? MPFRecCalMCEE { get; set; }

    public decimal? MPFRecCalVCRI { get; set; }

    public decimal? MPFRecCalVCER { get; set; }

    public decimal? MPFRecCalVCEE { get; set; }

    public decimal? MPFRecActMCRI { get; set; }

    public decimal? MPFRecActMCER { get; set; }

    public decimal? MPFRecActMCEE { get; set; }

    public decimal? MPFRecActVCRI { get; set; }

    public decimal? MPFRecActVCER { get; set; }

    public decimal? MPFRecActVCEE { get; set; }

    public int? CostCenterID { get; set; }
}