// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class MPFSchemeCessationReason
{
    public int MPFSchemeCessationReasonID { get; set; }

    public int? MPFSchemeID { get; set; }

    public string MPFSchemeCessationReasonCode { get; set; }

    public string MPFSchemeCessationReasonDesc { get; set; }
}