// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class MPFScheme
{
    public int MPFSchemeID { get; set; }

    public string MPFSchemeCode { get; set; }

    public string MPFSchemeDesc { get; set; }

    public string MPFSchemeTrusteeCode { get; set; }
}