// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class MPFSchemeCessationReasonMapping
{
    public int MPFSchemeCessationReasonMappingID { get; set; }

    public int? MPFSchemeCessationReasonID { get; set; }

    public int? CessationReasonID { get; set; }
}