// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class Nationality
{
    public int NationalityID { get; set; }

    public string NationalityCode { get; set; }

    public string NationalityDesc { get; set; }
}