// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class ORSOPlanDetail
{
    public int ORSOPlanDetailID { get; set; }

    public int? ORSOPlanID { get; set; }

    public int? ORSOPlanDetailYearOfService { get; set; }

    public decimal? ORSOPlanDetailER { get; set; }

    public decimal? ORSOPlanDetailERFix { get; set; }

    public decimal? ORSOPlanDetailEE { get; set; }

    public decimal? ORSOPlanDetailEEFix { get; set; }
}