// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class ORSOPlan
{
    public int ORSOPlanID { get; set; }

    public string ORSOPlanCode { get; set; }

    public string ORSOPlanDesc { get; set; }

    public string ORSOPlanSchemeNo { get; set; }

    public string ORSOPlanCompanyName { get; set; }

    public string ORSOPlanPayCenter { get; set; }

    public decimal? ORSOPlanMaxEmployerVC { get; set; }

    public decimal? ORSOPlanMaxEmployeeVC { get; set; }

    public int? ORSOPlanEmployerDecimalPlace { get; set; }

    public string ORSOPlanEmployerRoundingRule { get; set; }

    public int? ORSOPlanEmployeeDecimalPlace { get; set; }

    public string ORSOPlanEmployeeRoundingRule { get; set; }

    public bool? ORSOPlanEmployerResidual { get; set; }

    public decimal? ORSOPlanEmployerResidualCAP { get; set; }

    public bool? ORSOPlanEmployeeResidual { get; set; }

    public decimal? ORSOPlanEmployeeResidualCAP { get; set; }

    public int? ORSOFirstContributionAfterCompleteMonth { get; set; }

    public int? ORSOPlanOverrideCostCenterID { get; set; }

    public int? ORSOPlanParentPlanID { get; set; }
}