// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class ORSORecord
{
    public int ORSORecordID { get; set; }

    public int EmpPayrollID { get; set; }

    public int ORSOPlanID { get; set; }

    public DateTime ORSORecPeriodFr { get; set; }

    public DateTime ORSORecPeriodTo { get; set; }

    public string ORSORecType { get; set; }

    public decimal? ORSORecCalRI { get; set; }

    public decimal? ORSORecCalER { get; set; }

    public decimal? ORSORecCalEE { get; set; }

    public decimal? ORSORecActRI { get; set; }

    public decimal? ORSORecActER { get; set; }

    public decimal? ORSORecActEE { get; set; }

    public int? CostCenterID { get; set; }
}