// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class OTClaim
{
    public int OTClaimID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? OTClaimDateFrom { get; set; }

    public DateTime? OTClaimDateTo { get; set; }

    public DateTime? OTClaimTimeFrom { get; set; }

    public DateTime? OTClaimTimeTo { get; set; }

    public double? OTClaimDuration { get; set; }

    public string OTClaimRemark { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public int? OTClaimCancelID { get; set; }

    public int? EmpRequestID { get; set; }

    public int? RequestOTClaimID { get; set; }

    public string SynID { get; set; }

    public string OTClaimUnit { get; set; }

    public int? OTClaimReasonID { get; set; }

    public int? OTClaimSupportingDocumentCount { get; set; }
}