// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class OTClaimCancel
{
    public int OTClaimCancelID { get; set; }

    public int? EmpID { get; set; }

    public int? OTClaimID { get; set; }

    public DateTime? OTClaimCancelCreateDateTime { get; set; }

    public string OTClaimCancelReason { get; set; }

    public int? EmpRequestID { get; set; }

    public int? RequestOTClaimCancelID { get; set; }
}