// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PaymentRecord
{
    public int PayRecID { get; set; }

    public int? EmpPayrollID { get; set; }

    public int? PaymentCodeID { get; set; }

    public decimal? PayRecCalAmount { get; set; }

    public decimal? PayRecActAmount { get; set; }

    public string CurrencyID { get; set; }

    public string PayRecMethod { get; set; }

    public int? EmpAccID { get; set; }

    public string PayRecType { get; set; }

    public string PayRecStatus { get; set; }

    public double? PayRecNumOfDayAdj { get; set; }

    public int? LeaveAppID { get; set; }

    public string PayRecRemark { get; set; }

    public string LeaveAppIDList { get; set; }

    public bool? PayRecIsRestDayPayment { get; set; }

    public int? CostCenterID { get; set; }

    public int? EmpRPIDforBP { get; set; }

    public DateTime? PayRecRefDate { get; set; }
}