// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PaymentType
{
    public int PaymentTypeID { get; set; }

    public string PaymentTypeCode { get; set; }

    public string PaymentTypeDesc { get; set; }
}