// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PaymentCalculationFormulaType
{
    public int PayCalFormulaTypeID { get; set; }

    public string PayCalFormulaTypeCode { get; set; }

    public string PayCalFormulaTypeCodeDesc { get; set; }

    public decimal? StdHourlyWage { get; set; }
}