// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PaymentCalculationFormula
{
    public int PayCalFormulaID { get; set; }

    public string PayCalFormulaCode { get; set; }

    public string PayCalFormulaCodeDesc { get; set; }

    public int? PayCalFormulaTypeID { get; set; }
}