// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PaymentCode
{
    public int PaymentCodeID { get; set; }

    public string PaymentCode1 { get; set; }

    public string PaymentCodeDesc { get; set; }

    public int PaymentTypeID { get; set; }

    public bool? PaymentCodeIsProrata { get; set; }

    public bool? PaymentCodeIsProrataLeave { get; set; }

    public bool? PaymentCodeIsMPF { get; set; }

    public bool? PaymentCodeIsTopUp { get; set; }

    public bool? PaymentCodeIsWages { get; set; }

    public bool? PaymentCodeIsORSO { get; set; }

    public int? PaymentCodeDecimalPlace { get; set; }

    public string PaymentCodeRoundingRule { get; set; }

    public bool? PaymentCodeHideInPaySlip { get; set; }

    public int? PaymentCodeDisplaySeqNo { get; set; }

    public bool? PaymentCodeNotRemoveContributionFromTopUp { get; set; }

    public bool? PaymentCodeRoundingRuleIsAbsoluteValue { get; set; }

    public bool? PaymentCodeIsProrataStatutoryHoliday { get; set; }

    public int? PaymentCodeIsHitRateBased { get; set; }

    public decimal? PaymentCodeDefaultRateAtMonth1 { get; set; }

    public decimal? PaymentCodeDefaultRateAtMonth2 { get; set; }

    public decimal? PaymentCodeDefaultRateAtMonth3 { get; set; }

    public string PaymentCodeCDesc { get; set; }

    public bool? PaymentCodeIsCasual { get; set; }

    public bool? RentReimbursePaidByER { get; set; }

    public bool? RentReimbursePaidByEE { get; set; }

    public bool? RentReimburseRefundedToEE { get; set; }

    public bool? RentReimbursePaidToERbyEE { get; set; }
}