// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PayrollProrataFormula
{
    public int PayFormID { get; set; }

    public string PayFormCode { get; set; }

    public string PayFormDesc { get; set; }

    public int? PayFormPaymentType { get; set; }

    public double? PayFormMultiplier { get; set; }

    public double? PayFormDivider { get; set; }

    public string PayFormIsSys { get; set; }

    public int? ReferencePayFormID { get; set; }

    public int? PayFormDecimalPlace { get; set; }

    public string PayFormRoundingRule { get; set; }
}