// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PayrollGroup
{
    public int PayGroupID { get; set; }

    public string PayGroupCode { get; set; }

    public string PayGroupDesc { get; set; }

    public string PayGroupFreq { get; set; }

    public int? PayGroupDefaultStartDay { get; set; }

    public int? PayGroupDefaultEndDay { get; set; }

    public DateTime? PayGroupNextStartDate { get; set; }

    public DateTime? PayGroupNextEndDate { get; set; }

    public int? CurrentPayPeriodID { get; set; }

    public int? PayGroupLeaveDeductFormula { get; set; }

    public int? PayGroupLeaveAllowFormula { get; set; }

    public int? PayGroupNewJoinFormula { get; set; }

    public int? PayGroupTerminatedFormula { get; set; }

    public int? PayGroupTerminatedALCompensationDailyFormula { get; set; }

    public int? PayGroupTerminatedALCompensationPaymentCodeID { get; set; }

    public string PayGroupTerminatedPaymentInLieuMonthlyBaseMethod { get; set; }

    public int? PayGroupTerminatedPaymentInLieuDailyFormula { get; set; }

    public int? PayGroupTerminatedPaymentInLieuERPaymentCodeID { get; set; }

    public int? PayGroupTerminatedPaymentInLieuEEPaymentCodeID { get; set; }

    public string PayGroupTerminatedLSPSPMonthlyBaseMethod { get; set; }

    public int? PayGroupTerminatedGovLSPPaymentCodeID { get; set; }

    public int? PayGroupTerminatedGovSPPaymentCodeID { get; set; }

    public int? PayGroupStatHolDeductFormula { get; set; }

    public int? PayGroupStatHolAllowFormula { get; set; }

    public int? PayGroupStatHolAllowPaymentCodeID { get; set; }

    public int? PayGroupStatHolDeductPaymentCodeID { get; set; }

    public bool? PayGroupPayAdvance { get; set; }

    public int? PayGroupStatHolEligiblePeriod { get; set; }

    public string PayGroupStatHolEligibleUnit { get; set; }

    public bool? PayGroupStatHolEligibleAfterProbation { get; set; }

    public int? PayGroupYEBStartPayrollMonth { get; set; }

    public int? PayGroupYEBMonthFrom { get; set; }

    public int? PayGroupYEBMonthTo { get; set; }

    public bool? PayGroupStatHolNextMonth { get; set; }

    public bool? PayGroupTerminatedALCompensationProrataEligibleCheckEveryLeaveYear { get; set; }

    public int? PayGroupTerminatedALCompensationProrataEligiblePeriod { get; set; }

    public string PayGroupTerminatedALCompensationProrataEligibleUnit { get; set; }

    public bool? PayGroupTerminatedALCompensationEligibleAfterProbation { get; set; }

    public int? PayGroupDefaultProrataFormula { get; set; }

    public bool? PayGroupRestDayHasWage { get; set; }

    public int? PayGroupRestDayProrataFormula { get; set; }

    public int? PayGroupAdditionalRemunerationPayCodeID { get; set; }

    public bool? PayGroupUseCNDForDailyHourlyPayment { get; set; }

    public bool? PayGroupPayAdvanceCompareTotalPaymentOnly { get; set; }

    public bool? PayGroupLunchTimeHasWage { get; set; }

    public int? PayGroupTerminatedALCompensationByEEPaymentCodeID { get; set; }

    public bool? PayGroupIsCNDProrata { get; set; }

    public int? PayGroupTerminatedRestDayCompensationDailyFormula { get; set; }

    public int? PayGroupTerminatedRestDayCompensationPaymentCodeID { get; set; }

    public int? PayGroupTerminatedStatutoryHolidayCompensationDailyFormula { get; set; }

    public int? PayGroupTerminatedStatutoryHolidayCompensationPaymentCodeID { get; set; }

    public bool? PayGroupTerminatedALCompensationIsSkipRoundingRule { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public bool? PayGroupIsSkipStatHol { get; set; }

    public int? PayGroupExistingFormula { get; set; }

    public bool? PayGroupStatHolEligibleSkipDeduction { get; set; }

    public int? PayGroupDefaultNextStartDay { get; set; }

    public int? PayGroupLeaveDefaultCutOffDay { get; set; }

    public int? PayGroupLeaveDefaultNextCutOffDay { get; set; }

    public bool? PayGroupIsStatHolUsePublicHoliday { get; set; }

    public int? PayGroupTerminatedALCompensationDailyFormulaAlternative { get; set; }

    public string PayGroupTerminatedPaymentInLieuMonthlyBaseMethodAlternative { get; set; }

    public int? PayGroupTerminatedPaymentInLieuDailyFormulaAlternative { get; set; }

    public string PayGroupTerminatedLSPSPMonthlyBaseMethodAlternative { get; set; }

    public bool? PayGroupIsPublic { get; set; }

    public int? PayGroupTerminatedCoSPPaymentCodeID { get; set; }

    public int? PayGroupTerminatedCoLSPPaymentCodeID { get; set; }

    public string PayGroupYEBMode { get; set; }
}