// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class PayrollPeriod
{
    public int PayPeriodID { get; set; }

    public int? PayGroupID { get; set; }

    public DateTime? PayPeriodFr { get; set; }

    public DateTime? PayPeriodTo { get; set; }

    public DateTime? PayPeriodLeaveCutOffDate { get; set; }

    public DateTime? PayPeriodAttnFr { get; set; }

    public DateTime? PayPeriodAttnTo { get; set; }

    public string PayPeriodStatus { get; set; }

    public DateTime? PayPeriodTrialRunDate { get; set; }

    public int? PayPeriodTrialRunBy { get; set; }

    public DateTime? PayPeriodConfirmDate { get; set; }

    public int? PayPeriodConfirmBy { get; set; }

    public DateTime? PayPeriodProcessEndDate { get; set; }

    public int? PayPeriodProcessEndBy { get; set; }

    public DateTime? PayPeriodRollbackDate { get; set; }

    public int? PayPeriodRollbackBy { get; set; }

    public bool? PayPeriodIsAutoCreate { get; set; }
}