// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class PayrollGroupLeaveCodeSetupOverride
{
    public int PayrollGroupLeaveCodeSetupOverrideID { get; set; }

    public int? PayGroupID { get; set; }

    public int? LeaveCodeID { get; set; }

    public int? PayrollGroupLeaveCodeSetupLeaveAllowPaymentCodeID { get; set; }

    public int? PayrollGroupLeaveCodeSetupLeaveAllowFormula { get; set; }

    public int? PayrollGroupLeaveCodeSetupLeaveDeductPaymentCodeID { get; set; }

    public int? PayrollGroupLeaveCodeSetupLeaveDeductFormula { get; set; }
}