// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PayrollBatch
{
    public int PayBatchID { get; set; }

    public DateTime? PayBatchConfirmDate { get; set; }

    public DateTime? PayBatchValueDate { get; set; }

    public DateTime? PayBatchFileGenDate { get; set; }

    public int? PayBatchFileGenBy { get; set; }

    public string PayBatchRemark { get; set; }

    public bool? PayBatchIsESSPaySlipRelease { get; set; }
}