// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class PayScale
{
    public int PayScaleID { get; set; }

    public string SchemeCode { get; set; }

    public string Capacity { get; set; }

    public decimal? FirstPoint { get; set; }

    public decimal? MidPoint { get; set; }

    public decimal? LastPoint { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}