// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class PermitType
{
    public int PermitTypeID { get; set; }

    public string PermitTypeCode { get; set; }

    public string PermitTypeDesc { get; set; }
}