// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class PlaceOfBirth
{
    public int PlaceOfBirthID { get; set; }

    public string PlaceOfBirthCode { get; set; }

    public string PlaceOfBirthDesc { get; set; }
}