// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class Position
{
    public int PositionID { get; set; }

    public string PositionCode { get; set; }

    public string PositionDesc { get; set; }

    public string PositionCapacity { get; set; }

    public string PositionCDesc { get; set; }

    public bool? PositionERosterIsRounding { get; set; }
}