// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PS_BackpayBatchDetail
{
    public int DetailID { get; set; }

    public DateTime? AnnounceDate { get; set; }

    public DateTime? EffectiveDate { get; set; }

    public DateTime? BackpayDate { get; set; }

    public string SchemeCode { get; set; }

    public decimal? Point { get; set; }

    public decimal? Salary { get; set; }

    public decimal? CurrentSalary { get; set; }

    public string PaymentCode { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}