// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PS_SalaryIncrementBatch
{
    public int BatchID { get; set; }

    public DateTime? AsAtDate { get; set; }

    public int? DeferredBatch { get; set; }

    public int? PaymentCodeID { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string Status { get; set; }

    public DateTime? UploadDateTime { get; set; }

    public int? UploadBy { get; set; }

    public DateTime? ConfirmDateTime { get; set; }

    public int? ConfirmBy { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}