// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class PS_SalaryIncrementBatchDetail
{
    public int DetailID { get; set; }

    public string SessionID { get; set; }

    public int? EmpID { get; set; }

    public int? EmpRPID { get; set; }

    public string SchemeCode { get; set; }

    public string Capacity { get; set; }

    public decimal? CurrentPoint { get; set; }

    public decimal? NewPoint { get; set; }

    public DateTime? CurrentReviewDate { get; set; }

    public DateTime? NewReviewDate { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}