// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class Qualification
{
    public int QualificationID { get; set; }

    public string QualificationCode { get; set; }

    public string QualificationDesc { get; set; }
}