// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class Rank
{
    public int RankID { get; set; }

    public string RankCode { get; set; }

    public string RankDesc { get; set; }
}