// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class ReminderType
{
    public int ReminderTypeID { get; set; }

    public string ReminderTypeCode { get; set; }

    public string ReminderTypeDesc { get; set; }
}