// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class ReportBuilder
{
    public int ReportBuilderID { get; set; }

    public string ReportModule { get; set; }

    public string SelectedFieldNames { get; set; }

    public string DBFilterExpressions { get; set; }

    public string ReportName { get; set; }
}