// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class RequestEmpEmergencyContact
{
    public int RequestEmpEmergencyContactID { get; set; }

    public int? RequestEmpID { get; set; }

    public int? EmpEmergencyContactID { get; set; }

    public string EmpEmergencyContactName { get; set; }

    public string OldEmpEmergencyContactName { get; set; }

    public string EmpEmergencyContactRelationship { get; set; }

    public string OldEmpEmergencyContactRelationship { get; set; }

    public string EmpEmergencyContactContactNo { get; set; }

    public string OldEmpEmergencyContactContactNo { get; set; }
}