// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class RequestOTClaim
{
    public int RequestOTClaimID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? RequestOTClaimEffectiveDate { get; set; }

    public DateTime? RequestOTClaimDateExpiry { get; set; }

    public DateTime? RequestOTClaimPeriodFrom { get; set; }

    public DateTime? RequestOTClaimPeriodTo { get; set; }

    public DateTime? RequestOTClaimHourFrom { get; set; }

    public DateTime? RequestOTClaimHourTo { get; set; }

    public double? RequestOTDuration { get; set; }

    public string RequestOTClaimRemark { get; set; }

    public DateTime? RequestOTClaimCreateDate { get; set; }

    public string RequestOTUnit { get; set; }

    public int? OTClaimReasonID { get; set; }

    public int? EmpRequestID { get; set; }

    public string RequestOTClaimReason { get; set; }

    public int? RequestOTClaimSupportingDocumentCount { get; set; }
}