// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class RequestOTClaimCancel
{
    public int RequestOTClaimCancelID { get; set; }

    public int? EmpID { get; set; }

    public int? OTClaimID { get; set; }

    public DateTime? RequestOTClaimCancelCreateDateTime { get; set; }

    public string RequestOTClaimCancelReason { get; set; }

    public string EmpRequestID { get; set; }
}