// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class RequestLateWaiveCancel
{
    public int RequestLateWaiveCancelID { get; set; }

    public int? EmpID { get; set; }

    public int? LateWaiveID { get; set; }

    public DateTime? RequestLateWaiveCancelCreateDateTime { get; set; }

    public string RequestLateWaiveCancelReason { get; set; }

    public string EmpRequestID { get; set; }
}