// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class RequestLeaveApplicationCancel
{
    public int RequestLeaveAppCancelID { get; set; }

    public int? EmpID { get; set; }

    public int? LeaveAppID { get; set; }

    public DateTime? RequestLeaveAppCancelCreateDateTime { get; set; }

    public string RequestLeaveAppCancelReason { get; set; }

    public int? EmpRequestID { get; set; }

    public int? LeaveCancelReasonID { get; set; }
}