// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class RequestLeaveApplication
{
    public int RequestLeaveAppID { get; set; }

    public int? EmpID { get; set; }

    public int? RequestLeaveCodeID { get; set; }

    public string RequestLeaveAppUnit { get; set; }

    public DateTime? RequestLeaveAppDateFrom { get; set; }

    public DateTime? RequestLeaveAppDateTo { get; set; }

    public DateTime? RequestLeaveAppTimeFrom { get; set; }

    public DateTime? RequestLeaveAppTimeTo { get; set; }

    public double? RequestLeaveDays { get; set; }

    public string RequestLeaveAppRemark { get; set; }

    public DateTime? RequestLeaveAppCreateDate { get; set; }

    public bool? RequestLeaveAppHasMedicalCertificate { get; set; }

    public double? RequestLeaveAppHours { get; set; }

    public string RequestLeaveAppDateFromAM { get; set; }

    public string RequestLeaveAppDateToAM { get; set; }

    public int? EmpRequestID { get; set; }

    public int? RequestLeaveAppSupportingDocumentCount { get; set; }
}