// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class RequestStatus
{
    public int RequestStatusID { get; set; }

    public string RequestStatusCode { get; set; }

    public string RequestStatusDesc { get; set; }

    public string RequestStatusPosition { get; set; }
}