// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class RequestLateWaive
{
    public int RequestLateWaiveID { get; set; }

    public int? EmpID { get; set; }

    public int? AttendanceRecordID { get; set; }

    public string RequestLateWaiveReason { get; set; }

    public DateTime? RequestLateWaiveCreateDate { get; set; }

    public int? LateWaiveReasonID { get; set; }

    public int? EmpRequestID { get; set; }
}