// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class RequestEmpPersonalInfo
{
    public int RequestEmpID { get; set; }

    public int? EmpID { get; set; }

    public string RequestEmpAlias { get; set; }

    public string RequestEmpMaritalStatus { get; set; }

    public string RequestEmpPassportNo { get; set; }

    public string RequestEmpPassportIssuedCountry { get; set; }

    public string RequestEmpNationality { get; set; }

    public DateTime? RequestEmpPassportExpiryDate { get; set; }

    public string RequestEmpHomePhoneNo { get; set; }

    public string RequestEmpMobileNo { get; set; }

    public string RequestEmpOfficePhoneNo { get; set; }

    public string RequestEmpEmail { get; set; }

    public string RequestEmpResAddr { get; set; }

    public string RequestEmpCorAdd { get; set; }

    public DateTime? RequestEmpCreateDate { get; set; }

    public string RequestEmpResAddrAreaCode { get; set; }

    public int? RequestEmpNationalityID { get; set; }

    public int? RequestEmpPassportIssuedCountryID { get; set; }

    public int? RequestEmpPlaceOfBirthID { get; set; }

    public string RequestEmpPlaceOfBirth { get; set; }

    public string EmpEmergencyContactName { get; set; }

    public string EmpEmergencyContactGender { get; set; }

    public string EmpEmergencyContactRelationship { get; set; }

    public string EmpEmergencyContactContactNoDay { get; set; }

    public string EmpEmergencyContactContactNoNight { get; set; }

    public string OldAlias { get; set; }

    public string OldMaritalStatus { get; set; }

    public string OldPassportNo { get; set; }

    public DateTime? OldPassportExpiryDate { get; set; }

    public string OldHomePhoneNo { get; set; }

    public string OldMobileNo { get; set; }

    public string OldOfficePhoneNo { get; set; }

    public string OldEmail { get; set; }

    public string OldResAddr { get; set; }

    public string OldCorAdd { get; set; }

    public string OldResAddrAreaCode { get; set; }

    public int? OldNationalityID { get; set; }

    public int? OldPassportIssuedCountryID { get; set; }

    public int? OldPlaceOfBirthID { get; set; }

    public int? EmpRequestID { get; set; }

    public int? RequestEmpEmergencyContactID { get; set; }

    public string OldEmpResAddrRoom { get; set; }

    public string RequestEmpResAddrRoom { get; set; }

    public string OldEmpResAddrFloor { get; set; }

    public string RequestEmpResAddrFloor { get; set; }

    public string OldEmpResAddrBlock { get; set; }

    public string RequestEmpResAddrBlock { get; set; }

    public string OldEmpResAddrBuilding { get; set; }

    public string RequestEmpResAddrBuilding { get; set; }

    public string OldEmpResAddrEstate { get; set; }

    public string RequestEmpResAddrEstate { get; set; }

    public string OldEmpResAddrStreet { get; set; }

    public string RequestEmpResAddrStreet { get; set; }

    public string OldEmpResAddrDistrict { get; set; }

    public string RequestEmpResAddrDistrict { get; set; }

    public string OldEmpResAddrOtherCity { get; set; }

    public string RequestEmpResAddrOtherCity { get; set; }

    public string OldEmpResAddrOtherCountry { get; set; }

    public string RequestEmpResAddrOtherCountry { get; set; }

    public string RequestEmpCorAddrAreaCode { get; set; }
}