// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class RosterTable
{
    public int RosterTableID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? RosterTableDate { get; set; }

    public int? RosterCodeID { get; set; }

    public int? LeaveAppID { get; set; }

    public DateTime? RosterTableOverrideInTime { get; set; }

    public DateTime? RosterTableOverrideOutTime { get; set; }
}