// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class RosterClientSite
{
    public int RosterClientSiteID { get; set; }

    public int? RosterClientID { get; set; }

    public string RosterClientSiteCode { get; set; }

    public string RosterClientSitePropertyName { get; set; }

    public string RosterClientSiteLocation { get; set; }

    public string RosterClientSiteInCharge { get; set; }

    public string RosterClientSiteInChargeContactNo { get; set; }

    public string RosterClientSitePremisesNature { get; set; }

    public string RosterClientSiteServiceHours { get; set; }

    public string RosterClientSiteShift { get; set; }

    public int? CostCenterID { get; set; }
}