// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class RosterCodeDetail
{
    public int RosterCodeDetailID { get; set; }

    public int? RosterCodeID { get; set; }

    public double? RosterCodeDetailNoOfHour { get; set; }

    public double? RosterCodeDetailRate { get; set; }
}