// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class RosterCode
{
    public int RosterCodeID { get; set; }

    public string RosterCode1 { get; set; }

    public string RosterCodeDesc { get; set; }

    public string RosterCodeType { get; set; }

    public DateTime? RosterCodeInTime { get; set; }

    public DateTime? RosterCodeOutTime { get; set; }

    public DateTime? RosterCodeGraceInTime { get; set; }

    public DateTime? RosterCodeGraceOutTime { get; set; }

    public bool? RosterCodeHasLunch { get; set; }

    public DateTime? RosterCodeLunchStartTime { get; set; }

    public DateTime? RosterCodeLunchEndTime { get; set; }

    public bool? RosterCodeLunchIsDeductWorkingHour { get; set; }

    public int? RosterCodeLunchDeductWorkingHourMinsUnit { get; set; }

    public string RosterCodeLunchDeductWorkingHourMinsRoundingRule { get; set; }

    public bool? RosterCodeHasOT { get; set; }

    public DateTime? RosterCodeOTStartTime { get; set; }

    public DateTime? RosterCodeOTEndTime { get; set; }

    public bool? RosterCodeIsOTStartFromOutTime { get; set; }

    public DateTime? RosterCodeCutOffTime { get; set; }

    public double? RosterCodeWorkingDayUnit { get; set; }

    public double? RosterCodeDailyWorkingHour { get; set; }

    public bool? RosterCodeCountWorkHourOnly { get; set; }

    public int? RosterCodeCountOTAfterWorkHourMin { get; set; }

    public int? RosterCodeOTMinsUnit { get; set; }

    public string RosterCodeOTMinsRoundingRule { get; set; }

    public int? RosterClientID { get; set; }

    public int? RosterClientSiteID { get; set; }

    public bool? RosterCodeIsOverrideHourlyPayment { get; set; }

    public decimal? RosterCodeOverrideHoulyAmount { get; set; }

    public int? LeaveCodeID { get; set; }

    public bool? RosterCodeUseHalfWorkingDaysHours { get; set; }

    public double? RosterCodeUseHalfWorkingDaysHoursMaxWorkingHours { get; set; }

    public string RosterCodeColorCode { get; set; }

    public double? RosterCodeLunchDurationHour { get; set; }

    public double? RosterCodeLunchDeductMinimumWorkHour { get; set; }

    public int? CostCenterID { get; set; }

    public bool? RosterCodeOTIncludeLunch { get; set; }

    public int? RosterCodeLateMinsUnit { get; set; }

    public string RosterCodeLateMinsRoundingRule { get; set; }

    public int? RosterCodeEarlyLeaveMinsUnit { get; set; }

    public string RosterCodeEarlyLeaveMinsRoundingRule { get; set; }

    public int? RosterCodeLunchLateMinsUnit { get; set; }

    public string RosterCodeLunchLateMinsRoundingRule { get; set; }

    public int? RosterCodeLunchEarlyLeaveMinsUnit { get; set; }

    public string RosterCodeLunchEarlyLeaveMinsRoundingRule { get; set; }

    public bool? RosterCodeOTShiftStartTimeForLate { get; set; }

    public int? RosterCodeOTShiftStartTimeLimit { get; set; }

    public DateTime? RosterCodeAMInTime { get; set; }

    public DateTime? RosterCodeAMOutTime { get; set; }

    public DateTime? RosterCodePMInTime { get; set; }

    public DateTime? RosterCodePMOutTime { get; set; }
}