// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class RosterCodeAdditionalPayment
{
    public int RosterCodeAdditionalPaymentID { get; set; }

    public int? RosterCodeID { get; set; }

    public int? PaymentCodeID { get; set; }

    public double? RosterCodeAdditionalPaymentAmount { get; set; }
}