// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class RosterTableGroup
{
    public int RosterTableGroupID { get; set; }

    public string RosterTableGroupCode { get; set; }

    public string RosterTableGroupDesc { get; set; }

    public int? RosterClientID { get; set; }

    public int? RosterClientSiteID { get; set; }

    public string RosterTableGroupExtendData { get; set; }

    public bool? RosterTableGroupIsTrustedAttendance { get; set; }
}