// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class RosterClient
{
    public int RosterClientID { get; set; }

    public string RosterClientCode { get; set; }

    public string RosterClientName { get; set; }

    public int? RosterClientMappingSiteCodeToHLevelID { get; set; }

    public int? CostCenterID { get; set; }
}