// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class SalesCommissionPlan
{
    public int SalesCommissionPlanID { get; set; }

    public string PlanCode { get; set; }

    public string PlanDesc { get; set; }

    public int? CommissionPaymentCodeID { get; set; }
}