// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class SalesCommissionPlanDetail
{
    public int SalesCommissionPlanDetailID { get; set; }

    public int? SalesCommissionPlanID { get; set; }

    public decimal? SalesAchievedFromPercent { get; set; }

    public decimal? SalesAchievedToPercent { get; set; }

    public decimal? CommissionRate { get; set; }

    public decimal? CommissionAmount { get; set; }
}