// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class ShiftDutyCode
{
    public int ShiftDutyCodeID { get; set; }

    public string ShiftDutyCode1 { get; set; }

    public string ShiftDutyCodeDesc { get; set; }

    public DateTime ShiftDutyFromTime { get; set; }

    public DateTime ShiftDutyToTime { get; set; }
}