// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class ShopSalesTarget
{
    public int SalesTargetID { get; set; }

    public int? CostCenterID { get; set; }

    public DateTime? CutoffDate { get; set; }

    public decimal? TargetSales { get; set; }

    public decimal? ShopHeadcount { get; set; }

    public decimal? ActualSales { get; set; }
}