// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class Skill
{
    public int SkillID { get; set; }

    public string SkillCode { get; set; }

    public string SkillDesc { get; set; }
}