// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class SkillLevel
{
    public int SkillLevelID { get; set; }

    public string SkillLevelCode { get; set; }

    public string SkillLevelDesc { get; set; }
}