// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class StaffType
{
    public int StaffTypeID { get; set; }

    public string StaffTypeCode { get; set; }

    public string StaffTypeDesc { get; set; }
}