// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class SupportingDocument
{
    public int FileID { get; set; }

    public string FileNature { get; set; }

    public int? EmpID { get; set; }

    public int? EventID { get; set; }

    public string EventType { get; set; }

    public string OriginalFilename { get; set; }

    public string StoringFilename { get; set; }

    public string Description { get; set; }

    public string FileContentType { get; set; }

    public DateTime? RetirementDate { get; set; }

    public DateTime? PhysicalFileRemovalDate { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }
}