// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class SystemFunctionEmailAlert
{
    public int SystemFunctionEmailAlertID { get; set; }

    public int? FunctionID { get; set; }

    public bool? SystemFunctionEmailAlertInsert { get; set; }

    public bool? SystemFunctionEmailAlertUpdate { get; set; }

    public bool? SystemFunctionEmailAlertDelete { get; set; }
}