// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TaxCompanyMap
{
    public int TaxCompMapID { get; set; }

    public int? TaxCompID { get; set; }

    public int? CompanyID { get; set; }
}