// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TaxCompany
{
    public int TaxCompID { get; set; }

    public string TaxCompEmployerName { get; set; }

    public string TaxCompEmployerAddress { get; set; }

    public string TaxCompSection { get; set; }

    public string TaxCompERN { get; set; }

    public string TaxCompDesignation { get; set; }

    public string TaxCompNameOfSignature { get; set; }
}