// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TaxEmpPlaceOfResidence
{
    public int TaxEmpPlaceID { get; set; }

    public int? TaxEmpID { get; set; }

    public string TaxEmpPlaceAddress { get; set; }

    public string TaxEmpPlaceNature { get; set; }

    public DateTime? TaxEmpPlacePeriodFr { get; set; }

    public DateTime? TaxEmpPlacePeriodTo { get; set; }

    public long? TaxEmpPlaceERRent { get; set; }

    public long? TaxEmpPlaceEERent { get; set; }

    public long? TaxEmpPlaceEERentRefunded { get; set; }

    public long? TaxEmpPlaceERRentByEE { get; set; }
}