// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TaxEmpPayment
{
    public int TaxEmpPayID { get; set; }

    public int? TaxEmpID { get; set; }

    public int? TaxPayID { get; set; }

    public string TaxEmpPayNature { get; set; }

    public DateTime? TaxEmpPayPeriodFr { get; set; }

    public DateTime? TaxEmpPayPeriodTo { get; set; }

    public long? TaxEmpPayAmount { get; set; }
}