// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TaxEmp
{
    public int TaxEmpID { get; set; }

    public int? TaxFormID { get; set; }

    public int? EmpID { get; set; }

    public int? TaxEmpSheetNo { get; set; }

    public string TaxEmpHKID { get; set; }

    public string TaxEmpStatus { get; set; }

    public string TaxEmpSurname { get; set; }

    public string TaxEmpOtherName { get; set; }

    public string TaxEmpChineseName { get; set; }

    public string TaxEmpSex { get; set; }

    public string TaxEmpMartialStatus { get; set; }

    public string TaxEmpPassportNo { get; set; }

    public string TaxEmpIssuedCountry { get; set; }

    public string TaxEmpSpouseName { get; set; }

    public string TaxEmpSpouseHKID { get; set; }

    public string TaxEmpSpousePassportNo { get; set; }

    public string TaxEmpSpouseIssuedCountry { get; set; }

    public string TaxEmpResAddr { get; set; }

    public string TaxEmpResAddrAreaCode { get; set; }

    public string TaxEmpCorAddr { get; set; }

    public string TaxEmpCapacity { get; set; }

    public string TaxEmpPartTimeEmployer { get; set; }

    public DateTime? TaxEmpStartDate { get; set; }

    public DateTime? TaxEmpEndDate { get; set; }

    public string TaxEmpCessationReason { get; set; }

    public int? TaxEmpPlaceOfResidenceIndicator { get; set; }

    public int? TaxEmpOvearseasIncomeIndicator { get; set; }

    public string TaxEmpOverseasCompanyAmount { get; set; }

    public string TaxEmpOverseasCompanyName { get; set; }

    public string TaxEmpOverseasCompanyAddress { get; set; }

    public string TaxEmpTaxFileNo { get; set; }

    public string TaxEmpRemark { get; set; }

    public string TaxEmpNewEmployerNameddress { get; set; }

    public string TaxEmpFutureCorAddr { get; set; }

    public DateTime? TaxEmpLeaveHKDate { get; set; }

    public string TaxEmpIsERBearTax { get; set; }

    public string TaxEmpIsMoneyHoldByOrdinance { get; set; }

    public double? TaxEmpHoldAmount { get; set; }

    public string TaxEmpReasonForNotHold { get; set; }

    public string TaxEmpReasonForDepartureReason { get; set; }

    public string TaxEmpReasonForDepartureOtherReason { get; set; }

    public string TaxEmpIsEEReturnHK { get; set; }

    public DateTime? TaxEmpEEReturnHKDate { get; set; }

    public string TaxEmpIsShareOptionsGrant { get; set; }

    public string TaxEmpShareOptionsGrantCount { get; set; }

    public DateTime? TaxEmpShareOptionsGrantDate { get; set; }

    public string TaxEmpPreviousEmployerNameddress { get; set; }

    public DateTime? TaxEmpGeneratedDate { get; set; }

    public int? TaxEmpGeneratedByUserID { get; set; }

    public bool? TaxEmpIsReleasePrintoutToESS { get; set; }

    public string TaxEmpSumWithheldAmount { get; set; }

    public int? TaxEmpSumWithheldIndicator { get; set; }

    public string TaxEmpCorAddrAreaCode { get; set; }

    public string TaxEmpCompanyEngName { get; set; }

    public string TaxEmpCompanyChiName { get; set; }

    public string TaxEmpBRN { get; set; }

    public string TaxEmpCompanyTel { get; set; }
}