// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TaxForm
{
    public int TaxFormID { get; set; }

    public int? TaxCompID { get; set; }

    public string TaxFormSection { get; set; }

    public string TaxFormERN { get; set; }

    public int? TaxFormYear { get; set; }

    public DateTime? TaxFormSubmissionDate { get; set; }

    public int? TaxFormBatchNo { get; set; }

    public string TaxFormEmployerName { get; set; }

    public string TaxFormEmployerAddress { get; set; }

    public string TaxFormType { get; set; }

    public string TaxFormVersion { get; set; }

    public string TaxFormNameOfSignature { get; set; }

    public string TaxFormDesignation { get; set; }
}