// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TaxPaymentMap
{
    public int TaxPayMapID { get; set; }

    public int? TaxPayID { get; set; }

    public int? PaymentCodeID { get; set; }
}