// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TaxPayment
{
    public int TaxPayID { get; set; }

    public string TaxFormType { get; set; }

    public string TaxPayCode { get; set; }

    public string TaxPayDesc { get; set; }

    public string TaxPayNature { get; set; }

    public string TaxPayIsShowNature { get; set; }
}