// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TempEmpPositionInfo
{
    public int TempEmpPosID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpPosEffFr { get; set; }

    public DateTime? EmpPosEffTo { get; set; }

    public int? CompanyID { get; set; }

    public int? PositionID { get; set; }

    public int? RankID { get; set; }

    public int? StaffTypeID { get; set; }

    public int? EmploymentTypeID { get; set; }

    public int? PayGroupID { get; set; }

    public int? LeavePlanID { get; set; }

    public int? YEBPlanID { get; set; }

    public int? EmpFirstAuthorizationGp { get; set; }

    public int? EmpSecondAuthorizationGp { get; set; }

    public int? AttendancePlanID { get; set; }

    public int? EmpPosDefaultRosterCodeID { get; set; }

    public int? WorkHourPatternID { get; set; }

    public int? RosterTableGroupID { get; set; }

    public int? EmpPosIsRosterTableGroupSupervisor { get; set; }

    public string EmpPosRemark { get; set; }

    public int? AuthorizationWorkFlowIDLeaveApp { get; set; }

    public int? AuthorizationWorkFlowIDEmpInfoModified { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public int? EmpPosIsLeavePlanResetEffectiveDate { get; set; }

    public string SynID { get; set; }

    public int? AuthorizationWorkFlowIDOTClaims { get; set; }

    public int? AuthorizationWorkFlowIDLateWaive { get; set; }

    public int? AuthorizationWorkFlowIDOTSBClaims { get; set; }

    public int? AuthorizationWorkFlowIDExpensesClaims { get; set; }

    public int? AuthorizationWorkFlowIDRentalReimbursement { get; set; }

    public int? AuthorizationWorkFlowIDFinancialExpensesClaims { get; set; }

    public int? OTSBPlanID { get; set; }

    public string EmpPosExternalTitle { get; set; }

    public string EmpPosReferenceCode { get; set; }

    public string EmpPosStandardHour { get; set; }

    public bool? IsIntergroupTransfer { get; set; }

    public bool? IsNewJoinDate { get; set; }

    public int? PositionHistoryReasonID { get; set; }

    public string PositionHistoryReason2 { get; set; }

    public double? ERosterContractedWorkHoursPerMonth { get; set; }

    public double? ERosterContractedWorkHoursPerDay { get; set; }
}