// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TempEmpRecurringPayment
{
    public int TempEmpRPID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpRPEffFr { get; set; }

    public DateTime? EmpRPEffTo { get; set; }

    public int? PayCodeID { get; set; }

    public decimal? EmpRPAmount { get; set; }

    public string CurrencyID { get; set; }

    public string EmpRPUnit { get; set; }

    public string EmpRPMethod { get; set; }

    public int? EmpAccID { get; set; }

    public string EmpRPRemark { get; set; }

    public bool? EmpRPIsNonPayrollItem { get; set; }

    public int? CostCenterID { get; set; }

    public bool? EmpRPUnitPeriodAsDaily { get; set; }

    public int? EmpRPUnitPeriodAsDailyPayFormID { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public string SchemeCode { get; set; }

    public string Capacity { get; set; }

    public decimal? Point { get; set; }

    public decimal? EmpRPBasicSalary { get; set; }

    public decimal? EmpRPFPS { get; set; }

    public string EmpRecurringPaymentAmountFormulaBaseMethod { get; set; }

    public int? EmpRecurringPaymentAmountFormulaPaymentCodeID { get; set; }

    public string EmpRecurringPaymentAmountFormulaMultipler { get; set; }

    public int? RecurringPaymentReasonID { get; set; }

    public string RecurringPaymentReason2 { get; set; }
}