// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TempEmpPersonalInfo
{
    public int EmpID { get; set; }

    public string EmpNo { get; set; }

    public string EmpStatus { get; set; }

    public string EmpTitle { get; set; }

    public string EmpEngSurname { get; set; }

    public string EmpEngOtherName { get; set; }

    public string EmpChiFullName { get; set; }

    public string EmpChiSurname { get; set; }

    public string EmpChiOtherName { get; set; }

    public string EmpAlias { get; set; }

    public string EmpHKID { get; set; }

    public string EmpGender { get; set; }

    public string EmpMaritalStatus { get; set; }

    public DateTime? EmpDateOfBirth { get; set; }

    public string EmpPlaceOfBirth { get; set; }

    public string EmpNationality { get; set; }

    public string EmpPassportNo { get; set; }

    public string EmpPassportIssuedCountry { get; set; }

    public DateTime? EmpPassportExpiryDate { get; set; }

    public string EmpResAddr { get; set; }

    public string EmpResAddrAreaCode { get; set; }

    public string EmpResAddrRoom { get; set; }

    public string EmpResAddrFloor { get; set; }

    public string EmpResAddrBlock { get; set; }

    public string EmpResAddrBuilding { get; set; }

    public string EmpResAddrEstate { get; set; }

    public string EmpResAddrStreet { get; set; }

    public string EmpResAddrDistrict { get; set; }

    public string EmpResAddrOtherCity { get; set; }

    public string EmpResAddrOtherCountry { get; set; }

    public string EmpCorAddr { get; set; }

    public string EmpCorAddrAreaCode { get; set; }

    public DateTime? EmpDateOfJoin { get; set; }

    public DateTime? EmpServiceDate { get; set; }

    public int? EmpNoticePeriod { get; set; }

    public string EmpNoticeUnit { get; set; }

    public int? EmpProbaPeriod { get; set; }

    public string EmpProbaUnit { get; set; }

    public DateTime? EmpProbaLastDate { get; set; }

    public string EmpEmail { get; set; }

    public string EmpHomePhoneNo { get; set; }

    public string EmpMobileNo { get; set; }

    public string EmpOfficePhoneNo { get; set; }

    public string Remark { get; set; }

    public int? PreviousEmpID { get; set; }

    public string EmpPW { get; set; }

    public string EmpInternalEmail { get; set; }

    public string EmpTimeCardNo { get; set; }

    public int? EmpIsOverrideMinimumWage { get; set; }

    public float? EmpOverrideMinimumHourlyRate { get; set; }

    public int? MasterEmpID { get; set; }

    public int? EmpIsCombinePaySlip { get; set; }

    public int? EmpIsCombineMPF { get; set; }

    public int? EmpIsCombineTax { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public DateTime? EmpNextSalaryIncrementDate { get; set; }

    public DateTime? EmpOriginalHireDate { get; set; }

    public int? EmpNationalityID { get; set; }

    public int? EmpPassportIssuedCountryID { get; set; }

    public int? EmpPlaceOfBirthID { get; set; }

    public DateTime? ExpatriateArrivalDate { get; set; }

    public string EmpESSLanguage { get; set; }

    public string RegistrationSource { get; set; }

    public string RegistrationSourceID { get; set; }

    public string phoneCountryCode { get; set; }

    public DateTime? ExpVisaIssueDate { get; set; }

    public int? FormalEmpID { get; set; }
}