// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TempEmpDependant
{
    public int EmpDependantID { get; set; }

    public int? EmpID { get; set; }

    public string EmpDependantSurname { get; set; }

    public string EmpDependantOtherName { get; set; }

    public string EmpDependantChineseName { get; set; }

    public string EmpDependantGender { get; set; }

    public string EmpDependantHKID { get; set; }

    public string EmpDependantPassportNo { get; set; }

    public string EmpDependantPassportIssuedCountry { get; set; }

    public string EmpDependantRelationship { get; set; }

    public DateTime? EmpDependantDateOfBirth { get; set; }

    public string SynID { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public int? EmpDependantMedicalSchemeInsured { get; set; }

    public DateTime? EmpDependantMedicalEffectiveDate { get; set; }

    public DateTime? EmpDependantExpiryDate { get; set; }
}