// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TempEmpWorkExp
{
    public int EmpWorkExpID { get; set; }

    public int? EmpID { get; set; }

    public int? EmpWorkExpFromYear { get; set; }

    public int? EmpWorkExpFromMonth { get; set; }

    public int? EmpWorkExpToYear { get; set; }

    public int? EmpWorkExpToMonth { get; set; }

    public string EmpWorkExpCompanyName { get; set; }

    public string EmpWorkExpPosition { get; set; }

    public string EmpWorkExpRemark { get; set; }

    public int? EmpWorkExpEmploymentTypeID { get; set; }

    public int? EmpWorkExpIsRelevantExperience { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}