// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TempEmpExtraFieldValue
{
    public int EmpExtraFieldValueID { get; set; }

    public int? EmpID { get; set; }

    public int? EmpExtraFieldID { get; set; }

    public string EmpExtraFieldValue { get; set; }
}