// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TempEmpRPWinson
{
    public int TempEmpRPWinsonID { get; set; }

    public int TempEmpRPID { get; set; }

    public string EmpRPShiftDutyCode { get; set; }

    public string EmpRPShiftDutyCodeDesc { get; set; }

    public int EmpRPPayCalFormulaID { get; set; }

    public decimal EmpRPNoPayLunchHour { get; set; }

    public decimal EmpRPPayLunchHour { get; set; }
}