// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TempEmpQualification
{
    public int EmpQualificationID { get; set; }

    public int? EmpID { get; set; }

    public int? QualificationID { get; set; }

    public DateTime? EmpQualificationFrom { get; set; }

    public DateTime? EmpQualificationTo { get; set; }

    public string EmpQualificationInstitution { get; set; }

    public string EmpQualificationRemark { get; set; }

    public string EmpQualificationLearningMethod { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }
}