// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TempEmpHierarchy
{
    public int TempEmpHierarchyID { get; set; }

    public int? EmpID { get; set; }

    public int? TempEmpPosID { get; set; }

    public int? HElementID { get; set; }

    public int? HLevelID { get; set; }
}