// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TextTransformation
{
    public int TextTransformationID { get; set; }

    public string TextTransformationOriginalString { get; set; }

    public string TextTransformationReplacedTo { get; set; }
}