// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TimeCardRecordBackup
{
    public int TimeCardRecordID { get; set; }

    public int? EmpID { get; set; }

    public string TimeCardRecordCardNo { get; set; }

    public DateTime? TimeCardRecordDateTime { get; set; }

    public string TimeCardRecordLocation { get; set; }

    public int? TimeCardRecordInOutIndex { get; set; }

    public string TimeCardRecordOriginalData { get; set; }

    public string TimeCardRecordRemark { get; set; }
}