// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TimeCardLocationMap
{
    public int TimeCardLocationMapID { get; set; }

    public string TimeCardLocationMapOriginalCode { get; set; }

    public string TimeCardLocationMapNewCode { get; set; }
}