// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class Trainer
{
    public int TrainerID { get; set; }

    public string TrainerName { get; set; }
}