// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class TrainingCourse
{
    public int TrainingCourseID { get; set; }

    public string TrainingCourseCode { get; set; }

    public string TrainingCourseName { get; set; }
}