// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TrainingSeminar
{
    public int TrainingSeminarID { get; set; }

    public int? TrainingCourseID { get; set; }

    public string TrainingSeminarDesc { get; set; }

    public DateTime? TrainingSeminarDateFrom { get; set; }

    public DateTime? TrainingSeminarDateTo { get; set; }

    public float? TrainingSeminarDuration { get; set; }

    public string TrainingSeminarDurationUnit { get; set; }

    public string TrainingSeminarTrainer { get; set; }
}