// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class TrainingProgram
{
    public int ProgramID { get; set; }

    public string ProgramCode { get; set; }

    public string ProgramName { get; set; }

    public string ProgramType { get; set; }

    public int? CategoryID { get; set; }

    public int? SubCategoryID { get; set; }
}