// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpQualification
{
    public int UploadEmpQualificationID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpQualificationID { get; set; }

    public int? EmpID { get; set; }

    public int? QualificationID { get; set; }

    public DateTime? EmpQualificationFrom { get; set; }

    public DateTime? EmpQualificationTo { get; set; }

    public string EmpQualificationInstitution { get; set; }

    public string EmpQualificationLearningMethod { get; set; }

    public string EmpQualificationRemark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}