// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadLeaveApplication
{
    public int UploadLeaveAppID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? LeaveAppID { get; set; }

    public int? EmpID { get; set; }

    public int? LeaveCodeID { get; set; }

    public string LeaveAppUnit { get; set; }

    public DateTime? LeaveAppDateFrom { get; set; }

    public DateTime? LeaveAppDateTo { get; set; }

    public DateTime? LeaveAppTimeFrom { get; set; }

    public DateTime? LeaveAppTimeTo { get; set; }

    public decimal? LeaveAppDays { get; set; }

    public decimal? LeaveAppHours { get; set; }

    public string LeaveAppRemark { get; set; }

    public int? LeaveAppNoPayProcess { get; set; }

    public int? LeaveAppHasMedicalCertificate { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public string LeaveAppDateFromAM { get; set; }

    public string LeaveAppDateToAM { get; set; }
}