// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpORSOPlan
{
    public int UploadEmpORSOID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpORSOID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpORSOEffFr { get; set; }

    public DateTime? EmpORSOEffTo { get; set; }

    public int? ORSOPlanID { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}