// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpPositionInfo
{
    public int UploadEmpPosID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpPosID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpPosEffFr { get; set; }

    public DateTime? EmpPosEffTo { get; set; }

    public int? CompanyID { get; set; }

    public int? PositionID { get; set; }

    public int? RankID { get; set; }

    public int? EmploymentTypeID { get; set; }

    public int? StaffTypeID { get; set; }

    public int? PayGroupID { get; set; }

    public int? LeavePlanID { get; set; }

    public int? EmpPosIsLeavePlanResetEffectiveDate { get; set; }

    public int? YEBPlanID { get; set; }

    public int? AuthorizationWorkFlowIDLeaveApp { get; set; }

    public int? AuthorizationWorkFlowIDEmpInfoModified { get; set; }

    public int? AttendancePlanID { get; set; }

    public int? EmpPosDefaultRosterCodeID { get; set; }

    public int? WorkHourPatternID { get; set; }

    public int? RosterTableGroupID { get; set; }

    public int? EmpPosIsRosterTableGroupSupervisor { get; set; }

    public string EmpPosRemark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public int? AuthorizationWorkFlowIDOTClaims { get; set; }

    public int? AuthorizationWorkFlowIDLateWaive { get; set; }
}