// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpSponsorshipBudget
{
    public int UploadEmpSponsorshipBudgetID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpSponsorshipID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public decimal? BudgetAmount { get; set; }

    public decimal? AvailableAmount { get; set; }

    public decimal? RefundedAmount { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}