// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpCasualPlan
{
    public int UploadEmpCasualID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpCasualID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpCasualEffFr { get; set; }

    public DateTime? EmpCasualEffTo { get; set; }

    public int? CasualPlanID { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}