// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpSkill
{
    public int UploadEmpSkillID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpSkillID { get; set; }

    public int? EmpID { get; set; }

    public int? SkillID { get; set; }

    public int? SkillLevelID { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}