// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadClaimsAndDeduction
{
    public int UploadCNDID { get; set; }

    public int EmpID { get; set; }

    public DateTime CNDEffDate { get; set; }

    public int PayCodeID { get; set; }

    public decimal CNDAmount { get; set; }

    public string CurrencyID { get; set; }

    public string CNDPayMethod { get; set; }

    public int? EmpAccID { get; set; }

    public int? CNDIsRestDayPayment { get; set; }

    public int? CostCenterID { get; set; }

    public string CNDRemark { get; set; }

    public float? CNDNumOfDayAdj { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}