// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpTrainingHistory
{
    public int UploadEmpTrainingHistoryID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpProgramID { get; set; }

    public int? EmpID { get; set; }

    public string ProgramType { get; set; }

    public int? ProgramID { get; set; }

    public string ProgramName { get; set; }

    public int? InstitutionID { get; set; }

    public string InstitutionName { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int? NoOfSession { get; set; }

    public int? VenueID { get; set; }

    public string VenueName { get; set; }

    public int? QualificationID { get; set; }

    public string QualificationName { get; set; }

    public DateTime? DateOfQualification { get; set; }

    public int? TrainingHours { get; set; }

    public int? TrainerID { get; set; }

    public string TrainerName { get; set; }

    public decimal? Cost { get; set; }

    public int? EmpSponsorshipID { get; set; }

    public DateTime? EmpSponsorshipStartDate { get; set; }

    public DateTime? EmpSponsorshipExpiryDate { get; set; }

    public decimal? AmountOfSponsorship { get; set; }

    public int? Refund { get; set; }

    public DateTime? DateOfRefund { get; set; }

    public decimal? RefundAmount { get; set; }

    public int? ServiceBond { get; set; }

    public DateTime? ServiceBondEndDate { get; set; }

    public string Remark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}