// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadCommissionAchievement
{
    public int UploadCAID { get; set; }

    public int EmpID { get; set; }

    public decimal CAPercent { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public DateTime? CAEffDate { get; set; }
}