// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpBankAccount
{
    public int UploadEmpBankAccountID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpBankAccountID { get; set; }

    public int? EmpID { get; set; }

    public string EmpBankCode { get; set; }

    public string EmpBranchCode { get; set; }

    public string EmpAccountNo { get; set; }

    public string EmpBankAccountHolderName { get; set; }

    public int? EmpAccDefault { get; set; }

    public string EmpBankAccountRemark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}