// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpContractTerm
{
    public int UploadEmpContractID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpContractID { get; set; }

    public int? EmpID { get; set; }

    public string EmpContractCompanyName { get; set; }

    public string EmpContractCompanyContactNo { get; set; }

    public string EmpContractCompanyAddr { get; set; }

    public DateTime? EmpContractEmployedFrom { get; set; }

    public DateTime? EmpContractEmployedTo { get; set; }

    public decimal? EmpContractGratuity { get; set; }

    public string CurrencyID { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}