// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpPlaceOfResidence
{
    public int UploadEmpPoRID { get; set; }

    public int? UploadEmpID { get; set; }

    public int EmpPoRID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpPoRFrom { get; set; }

    public DateTime? EmpPoRTo { get; set; }

    public string EmpPoRLandLord { get; set; }

    public string EmpPoRLandLordAddr { get; set; }

    public string EmpPoRPropertyAddr { get; set; }

    public string EmpPoRNature { get; set; }

    public decimal EmpPoRPayToLandER { get; set; }

    public decimal EmpPoRPayToLandEE { get; set; }

    public decimal EmpPoRRefundToEE { get; set; }

    public decimal EmpPoRPayToERByEE { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}