// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadLeaveBalanceAdjustment
{
    public int UploadLeaveBalAdjID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? LeaveBalAdjID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? LeaveBalAdjDate { get; set; }

    public int? LeaveTypeID { get; set; }

    public string LeaveBalAdjType { get; set; }

    public float? LeaveBalAdjValue { get; set; }

    public string LeaveBalAdjRemark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public string LeaveBalAdjUnit { get; set; }
}