// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpMPFPlan
{
    public int UploadEmpMPFID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpMPFID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpMPFEffFr { get; set; }

    public DateTime? EmpMPFEffTo { get; set; }

    public int? MPFPlanID { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public string EmpMPFPlanEmployeeType { get; set; }

    public DateTime? EmpMPFPlanPreviousEmploymentDate { get; set; }

    public DateTime? EmpMPFPlanVisaIssueDate { get; set; }

    public string EmpMPFPlanMemberAccount { get; set; }

    public string EmpMPFPlanDefaultMemberClass { get; set; }
}