// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpRosterTableGroup
{
    public int UploadEmpRosterTableGroupID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpRosterTableGroupID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpRosterTableGroupEffFr { get; set; }

    public DateTime? EmpRosterTableGroupEffTo { get; set; }

    public int? RosterTableGroupID { get; set; }

    public int? EmpRosterTableGroupIsSupervisor { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public int? EmpRosterTableGroupIsShareable { get; set; }
}