// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpWorkExp
{
    public int UploadEmpWorkExpID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpWorkExpID { get; set; }

    public int? EmpID { get; set; }

    public int? EmpWorkExpFromYear { get; set; }

    public int? EmpWorkExpFromMonth { get; set; }

    public int? EmpWorkExpToYear { get; set; }

    public int? EmpWorkExpToMonth { get; set; }

    public string EmpWorkExpCompanyName { get; set; }

    public string EmpWorkExpPosition { get; set; }

    public int? EmpWorkExpEmploymentTypeID { get; set; }

    public int? EmpWorkExpIsRelevantExperience { get; set; }

    public string EmpWorkExpRemark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}