// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpSpouse
{
    public int UploadEmpSpouseID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpSpouseID { get; set; }

    public int? EmpID { get; set; }

    public string EmpSpouseSurname { get; set; }

    public string EmpSpouseOtherName { get; set; }

    public string EmpSpouseChineseName { get; set; }

    public DateTime? EmpSpouseDateOfBirth { get; set; }

    public string EmpSpouseHKID { get; set; }

    public string EmpSpousePassportNo { get; set; }

    public string EmpSpousePassportIssuedCountry { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public string EmpGender { get; set; }

    public int? EmpIsMedicalSchemaInsured { get; set; }

    public DateTime? EmpMedicalEffectiveDate { get; set; }

    public DateTime? EmpMedicalExpiryDate { get; set; }
}