// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpFinalPayment
{
    public int UploadEmpFinalPayID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? UploadEmpAccID { get; set; }

    public int? EmpFinalPayID { get; set; }

    public int? EmpID { get; set; }

    public int? PayCodeID { get; set; }

    public decimal? EmpFinalPayAmount { get; set; }

    public string CurrencyID { get; set; }

    public string EmpFinalPayMethod { get; set; }

    public int? EmpAccID { get; set; }

    public int? EmpFinalPayIsAutoGen { get; set; }

    public float? EmpFinalPayNumOfDayAdj { get; set; }

    public int? LeaveAppID { get; set; }

    public string PayRecID { get; set; }

    public int? CostCenterID { get; set; }

    public string EmpFinalPayRemark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}