// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadTimeCardRecord
{
    public int UploadTimeCardRecordID { get; set; }

    public int? TimeCardRecordID { get; set; }

    public int? EmpID { get; set; }

    public string TimeCardRecordCardNo { get; set; }

    public DateTime? TimeCardRecordDateTime { get; set; }

    public string TimeCardRecordLocation { get; set; }

    public int? TimeCardRecordInOutIndex { get; set; }

    public string TimeCardRecordOriginalData { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public string TimeCardRecordRemark { get; set; }
}