// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpEmergencyContact
{
    public int UploadEmpEmergencyContactID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpEmergencyContactID { get; set; }

    public int? EmpID { get; set; }

    public string EmpEmergencyContactName { get; set; }

    public string EmpEmergencyContactGender { get; set; }

    public string EmpEmergencyContactRelationship { get; set; }

    public string EmpEmergencyContactContactNo { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}