// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpPermit
{
    public int UploadEmpPermitID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpPermitID { get; set; }

    public int? EmpID { get; set; }

    public int? PermitTypeID { get; set; }

    public string EmpPermitNo { get; set; }

    public DateTime? EmpPermitIssueDate { get; set; }

    public DateTime? EmpPermitExpiryDate { get; set; }

    public string EmpPermitRemark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}