// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpWorkingSummary
{
    public int UploadEmpWorkingSummaryID { get; set; }

    public int? EmpWorkingSummaryID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpWorkingSummaryAsOfDate { get; set; }

    public float? EmpWorkingSummaryRestDayEntitled { get; set; }

    public float? EmpWorkingSummaryRestDayTaken { get; set; }

    public float? EmpWorkingSummaryTotalWorkingDays { get; set; }

    public float? EmpWorkingSummaryTotalWorkingHours { get; set; }

    public float? EmpWorkingSummaryTotalLunchTimeHours { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public float? EmpWorkingSummaryTotalStatutoryHoliday { get; set; }

    public float? EmpWorkingSummaryTotalLeaveDaysTaken { get; set; }

    public float? EmpWorkingSummaryExpectedTotalWorkingHours { get; set; }

    public float? EmpWorkingSummaryTotalOvertimeMinutes { get; set; }

    public float? EmpWorkingSummaryTotalLateMinutes { get; set; }

    public float? EmpWorkingSummaryTotalEarlyLeaveMinutes { get; set; }
}