// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadCompensationLeaveEntitle
{
    public int UploadCompensationLeaveEntitleID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? CompensationLeaveEntitleID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? CompensationLeaveEntitleEffectiveDate { get; set; }

    public DateTime? CompensationLeaveEntitleClaimPeriodFrom { get; set; }

    public DateTime? CompensationLeaveEntitleClaimPeriodTo { get; set; }

    public DateTime? CompensationLeaveEntitleClaimHourFrom { get; set; }

    public DateTime? CompensationLeaveEntitleClaimHourTo { get; set; }

    public float? CompensationLeaveEntitleDuration { get; set; }

    public DateTime? CompensationLeaveEntitleDateExpiry { get; set; }

    public string CompensationLeaveEntitleApprovedBy { get; set; }

    public int? CompensationLeaveEntitleIsAutoGenerated { get; set; }

    public string CompensationLeaveEntitleRemark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public string CompensationLeaveEntitleUnit { get; set; }

    public int? OTClaimReasonID { get; set; }
}