// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpAppraisal
{
    public int UploadEmpAppraisalID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpAppraisalID { get; set; }

    public int EmpID { get; set; }

    public DateTime? EmpAppraisalDate { get; set; }

    public decimal? EmpAppraisalScore { get; set; }

    public string EmpAppraisalRate { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}