// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpTermination
{
    public int UploadEmpTerminationID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpTerminationID { get; set; }

    public int? EmpID { get; set; }

    public int? CessationReasonID { get; set; }

    public DateTime? EmpTermResignDate { get; set; }

    public int? EmpTermNoticePeriod { get; set; }

    public string EmpTermNoticeUnit { get; set; }

    public DateTime? EmpTermLastDate { get; set; }

    public string EmpTermRemark { get; set; }

    public int? EmpTermIsTransferCompany { get; set; }

    public int? NewEmpID { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}