// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpAVCPlan
{
    public int UploadEmpAVCID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpAVCID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpAVCEffFr { get; set; }

    public DateTime? EmpAVCEffTo { get; set; }

    public int? AVCPlanID { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}