// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadShopActualSale
{
    public int UploadID { get; set; }

    public int? CostCenterID { get; set; }

    public DateTime? CutoffDate { get; set; }

    public decimal? ActualSales { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}