// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpBenefit
{
    public int UploadEmpBenefitID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpBenefitID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpBenefitEffectiveDate { get; set; }

    public DateTime? EmpBenefitExpiryDate { get; set; }

    public int? EmpBenefitPlanID { get; set; }

    public decimal? EmpBenefitERPremium { get; set; }

    public decimal? EmpBenefitEEPremium { get; set; }

    public decimal? EmpBenefitChildPremium { get; set; }

    public decimal? EmpBenefitSpousePremium { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}