// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpRecurringPayment
{
    public int UploadEmpRPID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? UploadEmpAccID { get; set; }

    public int? EmpRPID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpRPEffFr { get; set; }

    public DateTime? EmpRPEffTo { get; set; }

    public int? PayCodeID { get; set; }

    public decimal? EmpRPAmount { get; set; }

    public string CurrencyID { get; set; }

    public string EmpRPUnit { get; set; }

    public string EmpRPMethod { get; set; }

    public int? EmpAccID { get; set; }

    public int? EmpRPIsNonPayrollItem { get; set; }

    public int? CostCenterID { get; set; }

    public string EmpRPRemark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }

    public string SchemeCode { get; set; }

    public string Capacity { get; set; }

    public decimal? Point { get; set; }

    public decimal? EmpRPBasicSalary { get; set; }

    public decimal? EmpRPFPS { get; set; }

    public string EmpRPShiftDutyCode { get; set; }

    public string EmpRPShiftDutyCodeDesc { get; set; }

    public int? EmpRPPayCalFormulaID { get; set; }

    public string EmpRecurringPaymentAmountFormulaBaseMethod { get; set; }

    public int? EmpRecurringPaymentAmountFormulaPaymentCodeID { get; set; }

    public string EmpRecurringPaymentAmountFormulaMultipler { get; set; }
}