// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpAppreciation
{
    public int UploadEmpAppreciationID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpAppreciationID { get; set; }

    public int EmpID { get; set; }

    public DateTime? EmpAppreciationDate { get; set; }

    public string EmpAppreciationSource { get; set; }

    public string EmpAppreciationHRAction { get; set; }

    public string EmpAppreciationRemarks { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}