// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadHSBCMPFFormImportTemplate
{
    public int UploadHSBCMPFFormImportTemplateID { get; set; }

    public int? EmpID { get; set; }

    public int? EmpMPFID { get; set; }

    public string EmployeeType { get; set; }

    public DateTime? ExpatriateArrivalDate { get; set; }

    public DateTime? ExpatriateVisaIssueDate { get; set; }

    public string EnrollmentType { get; set; }

    public DateTime? DateJoinErMPF { get; set; }

    public DateTime? FirstDateJoinErMPF { get; set; }

    public DateTime? ErSchemeTransferDateJoinErMPF { get; set; }

    public DateTime? ErSchemeTransferEffDate { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime? TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}