// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UploadEmpBeneficiary
{
    public int UploadEmpBeneficiariesID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpBeneficiariesID { get; set; }

    public int? EmpID { get; set; }

    public string EmpBeneficiariesName { get; set; }

    public decimal? EmpBeneficiariesShare { get; set; }

    public string EmpBeneficiariesHKID { get; set; }

    public string EmpBeneficiariesRelation { get; set; }

    public string EmpBeneficiariesAddress { get; set; }

    public string EmpBeneficiariesDistrict { get; set; }

    public string EmpBeneficiariesArea { get; set; }

    public string EmpBeneficiariesCountry { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}