// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpCostCenterDetail
{
    public int UploadEmpCostCenterDetailID { get; set; }

    public int? UploadEmpCostCenterID { get; set; }

    public int? EmpCostCenterDetailID { get; set; }

    public int? EmpCostCenterID { get; set; }

    public int? CostCenterID { get; set; }

    public float? EmpCostCenterPercentage { get; set; }

    public int? EmpCostCenterDetailIsDefault { get; set; }
}