// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UploadEmpWorkInjuryRecord
{
    public int UploadEmpWorkInjuryRecordID { get; set; }

    public int? UploadEmpID { get; set; }

    public int? EmpWorkInjuryRecordID { get; set; }

    public int? EmpID { get; set; }

    public DateTime? EmpWorkInjuryRecordAccidentDate { get; set; }

    public string EmpWorkInjuryRecordAccidentLocation { get; set; }

    public string EmpWorkInjuryRecordAccidentReason { get; set; }

    public string EmpWorkInjuryRecordInjuryNature { get; set; }

    public DateTime? EmpWorkInjuryRecordReportedDate { get; set; }

    public DateTime? EmpWorkInjuryRecordChequeReceivedDate { get; set; }

    public DateTime? EmpWorkInjuryRecordSettleDate { get; set; }

    public string EmpWorkInjuryRecordRemark { get; set; }

    public string SynID { get; set; }

    public string SessionID { get; set; }

    public DateTime TransactionDate { get; set; }

    public string ImportAction { get; set; }

    public string ModifiedFieldList { get; set; }
}