// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UserTask
{
    public int UserTaskID { get; set; }

    public int? ClientID { get; set; }

    public int? UserID { get; set; }

    public string TaskSource { get; set; }

    public int? AsyncTaskID { get; set; }

    public DateTime? SubmitDateTime { get; set; }

    public string TaskParameter { get; set; }

    public string TaskStatus { get; set; }

    public DateTime? Heartbeat { get; set; }

    public DateTime? TaskStartDateTime { get; set; }

    public DateTime? TaskEndDateTime { get; set; }

    public int? ElapsedTime { get; set; }

    public string ReturnMessage { get; set; }

    public int? MaxRetry { get; set; }

    public int? RetryCount { get; set; }

    public int? RetryInterval { get; set; }

    public DateTime? LastExecutionDateTime { get; set; }
}