// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UserGroup
{
    public int UserGroupID { get; set; }

    public string UserGroupName { get; set; }

    public string UserGroupDesc { get; set; }
}