// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UserReminderOption
{
    public int UserReminderOptionID { get; set; }

    public int? UserID { get; set; }

    public int? ReminderTypeID { get; set; }

    public int? UserReminderOptionRemindDaysBefore { get; set; }

    public int? UserReminderOptionRemindDaysAfter { get; set; }
}