// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UserCompany
{
    public int UserCompanyID { get; set; }

    public int? UserID { get; set; }

    public int? CompanyID { get; set; }
}