// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class UserGroupFunction
{
    public int UserGroupFunctionID { get; set; }

    public int? UserGroupID { get; set; }

    public int? FunctionID { get; set; }

    public int? FunctionAllowRead { get; set; }

    public int? FunctionAllowWrite { get; set; }
}