// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Tenant.Entities;

public partial class UserGroupAccess
{
    public int UserGroupAccessID { get; set; }

    public int? UserID { get; set; }

    public int? UserGroupID { get; set; }
}