// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class User
{
    public int UserID { get; set; }

    public string LoginID { get; set; }

    public string UserName { get; set; }

    public string UserPassword { get; set; }

    public string UserAccountStatus { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public bool? UserChangePassword { get; set; }

    public string UserChangePasswordUnit { get; set; }

    public int? UserChangePasswordPeriod { get; set; }

    public DateTime? UserChangePasswordDate { get; set; }

    public int? FailCount { get; set; }

    public string UserLanguage { get; set; }

    public bool? UserIsKeepConnected { get; set; }

    public bool? UsersCannotCreateUsersWithMorePermission { get; set; }

    public string UserEmail { get; set; }

    public string UserMobileNo { get; set; }
}