// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class Venue
{
    public int VenueID { get; set; }

    public string VenueCode { get; set; }

    public string VenueName { get; set; }
}