// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class WorkHourPattern
{
    public int WorkHourPatternID { get; set; }

    public string WorkHourPatternCode { get; set; }

    public string WorkHourPatternDesc { get; set; }

    public string WorkHourPatternWorkDayDetermineMethod { get; set; }

    public int? WorkHourPatternSunDefaultRosterCodeID { get; set; }

    public double? WorkHourPatternSunDefaultDayUnit { get; set; }

    public int? WorkHourPatternMonDefaultRosterCodeID { get; set; }

    public double? WorkHourPatternMonDefaultDayUnit { get; set; }

    public int? WorkHourPatternTueDefaultRosterCodeID { get; set; }

    public double? WorkHourPatternTueDefaultDayUnit { get; set; }

    public int? WorkHourPatternWedDefaultRosterCodeID { get; set; }

    public double? WorkHourPatternWedDefaultDayUnit { get; set; }

    public int? WorkHourPatternThuDefaultRosterCodeID { get; set; }

    public double? WorkHourPatternThuDefaultDayUnit { get; set; }

    public int? WorkHourPatternFriDefaultRosterCodeID { get; set; }

    public double? WorkHourPatternFriDefaultDayUnit { get; set; }

    public int? WorkHourPatternSatDefaultRosterCodeID { get; set; }

    public double? WorkHourPatternSatDefaultDayUnit { get; set; }

    public bool? WorkHourPatternUseStatutoryHolidayTable { get; set; }

    public bool? WorkHourPatternUsePublicHolidayTable { get; set; }

    public int? WorkHourPatternStatutoryHolidayDefaultRosterCodeID { get; set; }

    public int? WorkHourPatternPublicHolidayDefaultRosterCodeID { get; set; }

    public double? WorkHourPatternContractWorkHoursPerDay { get; set; }

    public double? WorkHourPatternContractLunchTimeHoursPerDay { get; set; }

    public double? WorkHourPatternSunWorkHoursPerDay { get; set; }

    public double? WorkHourPatternSunLunchTimeHoursPerDay { get; set; }

    public double? WorkHourPatternMonWorkHoursPerDay { get; set; }

    public double? WorkHourPatternMonLunchTimeHoursPerDay { get; set; }

    public double? WorkHourPatternTueWorkHoursPerDay { get; set; }

    public double? WorkHourPatternTueLunchTimeHoursPerDay { get; set; }

    public double? WorkHourPatternWedWorkHoursPerDay { get; set; }

    public double? WorkHourPatternWedLunchTimeHoursPerDay { get; set; }

    public double? WorkHourPatternThuWorkHoursPerDay { get; set; }

    public double? WorkHourPatternThuLunchTimeHoursPerDay { get; set; }

    public double? WorkHourPatternFriWorkHoursPerDay { get; set; }

    public double? WorkHourPatternFriLunchTimeHoursPerDay { get; set; }

    public double? WorkHourPatternSatWorkHoursPerDay { get; set; }

    public double? WorkHourPatternSatLunchTimeHoursPerDay { get; set; }
}