// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Tenant.Entities;

public partial class YEBPlan
{
    public int YEBPlanID { get; set; }

    public string YEBPlanCode { get; set; }

    public string YEBPlanDesc { get; set; }

    public string YEBPlanPaymentBaseMethod { get; set; }

    public int? YEBPlanRPPaymentCodeID { get; set; }

    public double? YEBPlanMultiplier { get; set; }

    public string YEBPlanProrataMethod { get; set; }

    public int? YEBPlanPaymentCodeID { get; set; }

    public int? YEBPlanIsEligibleAfterProbation { get; set; }

    public int? YEBPlanEligiblePeriod { get; set; }

    public string YEBPlanEligibleUnit { get; set; }

    public int? YEBPlanIsGlobal { get; set; }

    public int? YEBPlanEligiblePeriodIsCheckEveryYEBYear { get; set; }

    public int? YEBPlanEligiblePeriodIsExcludeMax3MonthsProbation { get; set; }

    public string YEBPlanRecurringBasicSalaryType { get; set; }

    public int? YEBPlanMonthsAfterProbation { get; set; }
}