// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Control.Entities;

public partial class ClientSource
{
    public int ClientSourceID { get; set; }

    public string ClientSourceName { get; set; }
}