// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Control.Entities;

public partial class CompanyInbox
{
    public int CompanyInboxID { get; set; }

    public int? CompanyDBID { get; set; }

    public string CompanyInboxSubject { get; set; }

    public int? CompanyInboxRelatedRecID { get; set; }

    public string CompanyInboxMessage { get; set; }

    public DateTime? CompanyInboxCreateDate { get; set; }

    public DateTime? CompanyInboxReadDate { get; set; }

    public DateTime? CompanyInboxDeleteDate { get; set; }

    public DateTime? CompanyInboxExpiryDate { get; set; }
}