// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Control.Entities;

public partial class CompanyAutopayFileSignature
{
    public int CompanyAutopayFileSignatureID { get; set; }

    public int? CompanyAutopayFileID { get; set; }

    public int? CompanyDBID { get; set; }

    public int? UserID { get; set; }

    public string CompanyAutopayFileSignatureUserName { get; set; }

    public DateTime? CompanyAutopayFileSignatureDateTime { get; set; }
}