// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class CompanyDatabase
{
    public int CompanyDBID { get; set; }

    public string CompanyDBClientCode { get; set; }

    public string CompanyDBClientContactPerson { get; set; }

    public string CompanyDBClientName { get; set; }

    public string CompanyDBClientAddress { get; set; }

    public int? DBServerID { get; set; }

    public string CompanyDBSchemaName { get; set; }

    public bool? CompanyDBIsActive { get; set; }

    public int? CompanyDBMaxCompany { get; set; }

    public int? CompanyDBMaxUser { get; set; }

    public string CompanyDBProductKey { get; set; }

    public string CompanyDBTrialKey { get; set; }

    public string CompanyDBAuthorizationCode { get; set; }

    public string CompanyDBClientBank { get; set; }

    public string CompanyDBResetDefaultUserLoginID { get; set; }

    public string CompanyDBResetDefaultUserPassword { get; set; }

    public int? CompanyDBMaxEmployee { get; set; }

    public bool? CompanyDBHasEChannel { get; set; }

    public bool? CompanyDBHasIMGR { get; set; }

    public bool? CompanyDBHasIStaff { get; set; }

    public int? CompanyDBInboxMaxQuotaMB { get; set; }

    public bool? CompanyDBAutopayFileHasHSBCHASE { get; set; }

    public bool? CompanyDBAutopayFileHasOthers { get; set; }

    public bool? CompanyDBHSBCINX1 { get; set; }

    public bool? CompanyDBHSBCIN61 { get; set; }

    public bool? CompanyDBHASEHAX1 { get; set; }

    public bool? CompanyDBHASEHA61 { get; set; }

    public string CompanyDBHSBCPayCenter { get; set; }

    public bool? CompanyDBMPFFileHasHSBCHASE { get; set; }

    public bool? CompanyDBMPFFileHasBCT { get; set; }

    public bool? CompanyDBMPFFileHasAIA { get; set; }

    public bool? CompanyDBMPFFileHasAXA { get; set; }

    public bool? CompanyDBMPFFileHasBOCI { get; set; }

    public bool? CompanyDBMPFFileHasManulife { get; set; }

    public bool? CompanyDBAutopayFileHasSCB { get; set; }

    public bool? CompanyDBAutopayFileHasBOCI { get; set; }

    public bool? CompanyDBMPFFileHasOthers { get; set; }

    public int? ClientSourceID { get; set; }

    public string CompanyConvenientCode { get; set; }

    public bool? CompanyDBEnableEESelfRegister { get; set; }

    public bool? CompanyDBMPFFileHasSunlife { get; set; }

    public bool? CompanyDBAIAREEA { get; set; }

    public bool? CompanyDBHasPeopleHub { get; set; }
}