// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class CompanyMPFFile
{
    public int CompanyMPFFileID { get; set; }

    public int? CompanyDBID { get; set; }

    public string CompanyMPFFileTrusteeCode { get; set; }

    public string CompanyMPFFileFileType { get; set; }

    public string CompanyMPFFileDataFileRelativePath { get; set; }

    public string CompanyMPFFileReportFileRelativePath { get; set; }

    public DateTime? CompanyMPFFileSubmitDateTime { get; set; }

    public DateTime? CompanyMPFFileConfirmDateTime { get; set; }

    public DateTime? CompanyMPFFileConsolidateDateTime { get; set; }

    public string CompanyMPFFileTransactionReference { get; set; }

    public int? HSBCExchangeProfileID { get; set; }

    public int? CompanyMPFFileSubmitEmpID { get; set; }

    public string CompanyMPFFileSubmitEmpName { get; set; }

    public int? CompanyMPFFileNewEECount { get; set; }

    public int? CompanyMPFFileExistingEECount { get; set; }

    public decimal? CompanyMPFFileBatchAmount { get; set; }

    public string CompanyMPFFileStatus { get; set; }

    public DateTime? CompanyMPFFile1stSignDateTime { get; set; }

    public string CompanyMPFFile1stSignEmpName { get; set; }

    public DateTime? CompanyMPFFile2ndSignDateTime { get; set; }

    public string CompanyMPFFile2ndSignEmpName { get; set; }

    public string CompanyMPFFileVersion { get; set; }

    public string CompanyMPFFileEmployerID { get; set; }

    public string CompanyMPFFilePayCenter { get; set; }

    public string CompanyMPFFileDescription { get; set; }

    public DateTime? CompanyMPFFileCancelDateTime { get; set; }
}