// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Control.Entities;

public partial class CompanyEnrollmentForm
{
    public int id { get; set; }

    public int? CompanyDBID { get; set; }

    public int? EmpID { get; set; }

    public string EmpNo { get; set; }

    public string EmpEngFullName { get; set; }

    public int? EmpFormDataID { get; set; }

    public int? EmpFormBodyID { get; set; }

    public DateTime? ErSubmitDateTime { get; set; }

    public DateTime? ToHSBCDateTime { get; set; }

    public string FormStatus { get; set; }

    public DateTime? UndoDateTime { get; set; }

    public int? UndoByUserID { get; set; }
}