// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Control.Entities;

public partial class CompanyMPFFileSignature
{
    public int CompanyMPFFileSignatureID { get; set; }

    public int? CompanyMPFFileID { get; set; }

    public int? CompanyDBID { get; set; }

    public int? UserID { get; set; }

    public string CompanyMPFFileSignatureUserName { get; set; }

    public DateTime? CompanyMPFFileSignatureDateTime { get; set; }
}