// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Control.Entities;

public partial class CompanyInboxAttachment
{
    public int CompanyInboxAttachmentID { get; set; }

    public int? CompanyInboxID { get; set; }

    public string CompanyInboxAttachmentOriginalFileName { get; set; }

    public string CompanyInboxAttachmentStoredFileName { get; set; }

    public int? CompanyInboxAttachmentIsCompressed { get; set; }

    public long? CompanyInboxAttachmentSize { get; set; }
}