// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class CompanyAutopayFile
{
    public int CompanyAutopayFileID { get; set; }

    public int? CompanyDBID { get; set; }

    public string CompanyAutopayFileBankCode { get; set; }

    public string CompanyAutopayFileDataFileRelativePath { get; set; }

    public string CompanyAutopayFileReportFileRelativePath { get; set; }

    public DateTime? CompanyAutopayFileSubmitDateTime { get; set; }

    public DateTime? CompanyAutopayFileConfirmDateTime { get; set; }

    public DateTime? CompanyAutopayFileConsolidateDateTime { get; set; }

    public string CompanyAutopayFileTransactionReference { get; set; }

    public int? HSBCExchangeProfileID { get; set; }

    public DateTime? CompanyAutopayFileValueDate { get; set; }

    public int? CompanyAutopayFileSubmitEmpID { get; set; }

    public string CompanyAutopayFileSubmitEmpName { get; set; }

    public int? CompanyAutopayFileInstructionsCount { get; set; }

    public string CompanyAutopayFileStatus { get; set; }

    public DateTime? CompanyAutopayFile1stSignDateTime { get; set; }

    public string CompanyAutopayFile1stSignEmpName { get; set; }

    public DateTime? CompanyAutopayFile2ndSignDateTime { get; set; }

    public string CompanyAutopayFile2ndSignEmpName { get; set; }

    public string CompanyAutopayFileBranchCode { get; set; }

    public string CompanyAutopayFileBankAccountNo { get; set; }

    public string CompanyAutopayFileVersion { get; set; }

    public decimal? CompanyAutopayFileBatchAmount { get; set; }

    public DateTime? CompanyAutopayFileCancelDateTime { get; set; }
}