// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class DatabaseServer
{
    public int DBServerID { get; set; }

    public string DBServerCode { get; set; }

    public string DBServerDBType { get; set; }

    public string DBServerLocation { get; set; }

    public string DBServerSAUserID { get; set; }

    public string DBServerSAPassword { get; set; }

    public string DBServerUserID { get; set; }

    public string DBServerPassword { get; set; }

    public bool? DBServerIsActive { get; set; }
}