// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class HSBCExchangeProfile
{
    public int HSBCExchangeProfileID { get; set; }

    public int? CompanyDBID { get; set; }

    public string HSBCExchangeProfileRemoteProfileID { get; set; }

    public string HSBCExchangeProfileBankCode { get; set; }

    public int? HSBCExchangeProfileIsLocked { get; set; }
}