// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class HSBCBankPaymentCode
{
    public int HSBCBankPaymentCodeID { get; set; }

    public int? CompanyDBID { get; set; }

    public string HSBCBankPaymentCodeBankAccountNo { get; set; }

    public string HSBCBankPaymentCode1 { get; set; }

    public string HSBCBankPaymentCodeAutoPayInOutFlag { get; set; }

    public int? HSBCExchangeProfileID { get; set; }
}