// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class iMGRAnnouncement
{
    public int iMGRAnnouncementID { get; set; }

    public string iMGRAnnouncementCode { get; set; }

    public DateTime? iMGRAnnouncementEffectiveDateFr { get; set; }

    public DateTime? iMGRAnnouncementEffectiveDateTo { get; set; }

    public string iMGRAnnouncementContent { get; set; }
}