// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class iStaffUserDeactivationLog
{
    public long Id { get; set; }

    public string AspNetUserId { get; set; }

    public int? AppClientId { get; set; }

    public int? AppUserId { get; set; }

    public string AppClientCode { get; set; }

    public string AppUserEmpNo { get; set; }

    public int? EmpTerminationId { get; set; }

    public DateTime? EmpTermLastDate { get; set; }

    public DateTime? DeactivationDateTime { get; set; }

    public string AppUserEmail { get; set; }

    public string AppUserPhoneNumber { get; set; }
}