// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class MPFEnrollmentForm
{
    public int MPFEnrollmentFormID { get; set; }

    public string MPFEnrollmentFormCode { get; set; }

    public DateTime? MPFEnrollmentFormSubmissionEffFr { get; set; }

    public DateTime? MPFEnrollmentFormSubmissionEffTo { get; set; }
}