// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Control.Entities;

public partial class MPFFollowUpAgreement
{
    public int id { get; set; }

    public int? ClientID { get; set; }

    public int? EmpID { get; set; }

    public string Surname { get; set; }

    public string OtherName { get; set; }

    public string ChineseName { get; set; }

    public string WorkPhoneNo { get; set; }

    public string HomePhoneNo { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public DateTime? AgreementDateTime { get; set; }

    public string TrusteeCode { get; set; }

    public string HKID { get; set; }

    public DateTime? SendToHSBCDateTime { get; set; }

    public int? EmpFormDataID { get; set; }
}