// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Control.Entities;

public partial class MPFSchemeEnrollmentForm
{
    public int MPFSchemeEnrollmentFormID { get; set; }

    public string MPFSchemeCode { get; set; }

    public string EnrollmentFormName { get; set; }

    public bool? IsDefaultForm { get; set; }
}