// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.Database.Control.Entities;

public partial class StatutoryHoliday
{
    public int StatutoryHolidayID { get; set; }

    public DateTime? StatutoryHolidayDate { get; set; }

    public string StatutoryHolidayDesc { get; set; }
}