// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class SystemParameter
{
    public string ParameterCode { get; set; }

    public string ParameterDesc { get; set; }

    public string ParameterValue { get; set; }
}