// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class temp1
{
    public int autoid { get; set; }

    public string ac { get; set; }

    public string profileID { get; set; }

    public string Paymentcode { get; set; }

    public string dir { get; set; }
}