// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class Token
{
    public int TokenID { get; set; }

    public string TokenValue { get; set; }

    public int? ClientID { get; set; }

    public int? EmpID { get; set; }

    public string ActionType { get; set; }

    public string AdditionalInfo { get; set; }

    public DateTime? TokenCreationDateTime { get; set; }

    public DateTime? TokenExpiryDateTime { get; set; }

    public DateTime? RecordCreatedDateTime { get; set; }

    public int? RecordCreatedBy { get; set; }

    public DateTime? RecordLastModifiedDateTime { get; set; }

    public int? RecordLastModifiedBy { get; set; }

    public string TokenBatchID { get; set; }

    public DateTime? TokenExerciseDateTime { get; set; }
}