// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class UserApiToken
{
    public int id { get; set; }

    public string Username { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenCreateDateTime { get; set; }

    public DateTime? RefreshTokenExpiryDateTime { get; set; }
}