// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMGR.LegacyData.Control.Entities;

public partial class UserFunction
{
    public int UserFunctionID { get; set; }

    public int? UserID { get; set; }

    public int? FunctionID { get; set; }
}